// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;
using OpenAI.Assistants;
using OpenAI.Audio;
using OpenAI.Batch;
using OpenAI.Chat;
using OpenAI.Containers;
using OpenAI.Embeddings;
using OpenAI.Files;
using OpenAI.FineTuning;
using OpenAI.Images;
using OpenAI.Models;
using OpenAI.Moderations;
using OpenAI.Realtime;
using OpenAI.VectorStores;
using OpenAI.Graders;
using OpenAI.Responses;

namespace OpenAI
{
    internal static partial class OpenAIModelFactory
    {
        public static GraderStringCheck GraderStringCheck(string name = default, string input = default, string reference = default, GraderStringCheckOperation operation = default)
        {
            return new GraderStringCheck(
                GraderType.StringCheck,
                additionalBinaryDataProperties: null,
                name,
                input,
                reference,
                operation);
        }

        public static Grader Grader(string kind = default)
        {
            return new UnknownGrader(new GraderType(kind), additionalBinaryDataProperties: null);
        }

        public static GraderTextSimilarity GraderTextSimilarity(string name = default, string input = default, string reference = default, GraderTextSimilarityEvaluationMetric evaluationMetric = default)
        {
            return new GraderTextSimilarity(
                GraderType.TextSimilarity,
                additionalBinaryDataProperties: null,
                name,
                input,
                reference,
                evaluationMetric);
        }

        public static GraderPython GraderPython(string name = default, string source = default, string imageTag = default)
        {
            return new GraderPython(GraderType.Python, additionalBinaryDataProperties: null, name, source, imageTag);
        }

        public static GraderMulti GraderMulti(string name = default, BinaryData graders = default, string calculateOutput = default)
        {
            return new GraderMulti(GraderType.Multi, additionalBinaryDataProperties: null, name, graders, calculateOutput);
        }
        public static RunGraderRequest RunGraderRequest(BinaryData grader = default, BinaryData item = default, string modelSample = default)
        {
            return new RunGraderRequest(grader, item, modelSample, additionalBinaryDataProperties: null);
        }

        public static RunGraderResponse RunGraderResponse(float reward = default, RunGraderResponseMetadata metadata = default, BinaryData subRewards = default, BinaryData modelGraderTokenUsagePerModel = default)
        {
            return new RunGraderResponse(reward, metadata, subRewards, modelGraderTokenUsagePerModel, additionalBinaryDataProperties: null);
        }

        public static RunGraderResponseMetadata RunGraderResponseMetadata(string name = default, string kind = default, RunGraderResponseMetadataErrors errors = default, float executionTime = default, BinaryData scores = default, int? tokenUsage = default, string sampledModelName = default)
        {
            return new RunGraderResponseMetadata(
                name,
                kind,
                errors,
                executionTime,
                scores,
                tokenUsage,
                sampledModelName,
                additionalBinaryDataProperties: null);
        }

        public static RunGraderResponseMetadataErrors RunGraderResponseMetadataErrors(bool formulaParseError = default, bool sampleParseError = default, bool truncatedObservationError = default, bool unresponsiveRewardError = default, bool invalidVariableError = default, bool otherError = default, bool pythonGraderServerError = default, string pythonGraderServerErrorType = default, bool pythonGraderRuntimeError = default, string pythonGraderRuntimeErrorDetails = default, bool modelGraderServerError = default, bool modelGraderRefusalError = default, bool modelGraderParseError = default, string modelGraderServerErrorDetails = default)
        {
            return new RunGraderResponseMetadataErrors(
                formulaParseError,
                sampleParseError,
                truncatedObservationError,
                unresponsiveRewardError,
                invalidVariableError,
                otherError,
                pythonGraderServerError,
                pythonGraderServerErrorType,
                pythonGraderRuntimeError,
                pythonGraderRuntimeErrorDetails,
                modelGraderServerError,
                modelGraderRefusalError,
                modelGraderParseError,
                modelGraderServerErrorDetails,
                additionalBinaryDataProperties: null);
        }

        public static ValidateGraderRequest ValidateGraderRequest(BinaryData grader = default)
        {
            return new ValidateGraderRequest(grader, additionalBinaryDataProperties: null);
        }

        public static ValidateGraderResponse ValidateGraderResponse(BinaryData grader = default)
        {
            return new ValidateGraderResponse(grader, additionalBinaryDataProperties: null);
        }
        public static FileSearchToolRankingOptions FileSearchToolRankingOptions(FileSearchToolRanker? ranker = default, float? scoreThreshold = default)
        {
            return new FileSearchToolRankingOptions(ranker, scoreThreshold, default);
        }
        public static WebSearchToolFilters WebSearchToolFilters(IEnumerable<string> allowedDomains = default)
        {
            allowedDomains ??= new ChangeTrackingList<string>();

            return new WebSearchToolFilters(allowedDomains.ToList(), default);
        }

        public static ImageGenerationToolInputImageMask ImageGenerationToolInputImageMask(string imageUrl = default, string fileId = default)
        {
            return new ImageGenerationToolInputImageMask(imageUrl, fileId, default);
        }

        public static McpToolFilter McpToolFilter(IEnumerable<string> toolNames = default, bool? isReadOnly = default)
        {
            toolNames ??= new ChangeTrackingList<string>();

            return new McpToolFilter(toolNames.ToList(), isReadOnly, default);
        }

        public static CreateResponseOptions CreateResponseOptions(IDictionary<string, string> metadata = default, float? temperature = default, int? topLogProbabilityCount = default, float? topP = default, string endUserId = default, string safetyIdentifier = default, ResponseServiceTier? serviceTier = default, string previousResponseId = default, string model = default, ResponseReasoningOptions reasoningOptions = default, bool? backgroundModeEnabled = default, int? maxOutputTokenCount = default, int? maxToolCallCount = default, string instructions = default, ResponseTextOptions textOptions = default, IEnumerable<ResponseTool> tools = default, ResponseToolChoice toolChoice = default, ResponseTruncationMode? truncationMode = default, IEnumerable<ResponseItem> inputItems = default, IEnumerable<IncludedResponseProperty> includedProperties = default, bool? parallelToolCallsEnabled = default, bool? storedOutputEnabled = default, bool? streamingEnabled = default, ResponseConversationOptions conversationOptions = default)
        {
            metadata ??= new ChangeTrackingDictionary<string, string>();
            tools ??= new ChangeTrackingList<ResponseTool>();
            inputItems ??= new ChangeTrackingList<ResponseItem>();
            includedProperties ??= new ChangeTrackingList<IncludedResponseProperty>();

            return new CreateResponseOptions(
                metadata,
                temperature,
                topLogProbabilityCount,
                topP,
                endUserId,
                safetyIdentifier,
                serviceTier,
                previousResponseId,
                model,
                reasoningOptions,
                backgroundModeEnabled,
                maxOutputTokenCount,
                maxToolCallCount,
                instructions,
                textOptions,
                tools.ToList(),
                toolChoice,
                truncationMode,
                inputItems.ToList(),
                includedProperties.ToList(),
                parallelToolCallsEnabled,
                storedOutputEnabled,
                streamingEnabled,
                conversationOptions,
                default);
        }

        public static ResponseTextOptions ResponseTextOptions(ResponseTextFormat textFormat = default)
        {
            return new ResponseTextOptions(textFormat, default);
        }

        public static ResponseMessageAnnotation ResponseMessageAnnotation(string kind = default)
        {
            return new InternalUnknownAnnotation(kind.ToResponseMessageAnnotationKind(), default);
        }

        public static FileCitationMessageAnnotation FileCitationMessageAnnotation(string fileId = default, int index = default, string filename = default)
        {
            return new FileCitationMessageAnnotation(ResponseMessageAnnotationKind.FileCitation, default, fileId, index, filename);
        }

        public static UriCitationMessageAnnotation UriCitationMessageAnnotation(Uri uri = default, int startIndex = default, int endIndex = default, string title = default)
        {
            return new UriCitationMessageAnnotation(
                ResponseMessageAnnotationKind.UriCitation,
                default,
                uri,
                startIndex,
                endIndex,
                title);
        }

        public static ContainerFileCitationMessageAnnotation ContainerFileCitationMessageAnnotation(string containerId = default, string fileId = default, int startIndex = default, int endIndex = default, string filename = default)
        {
            return new ContainerFileCitationMessageAnnotation(
                ResponseMessageAnnotationKind.ContainerFileCitation,
                default,
                containerId,
                fileId,
                startIndex,
                endIndex,
                filename);
        }

        public static FilePathMessageAnnotation FilePathMessageAnnotation(string fileId = default, int index = default)
        {
            return new FilePathMessageAnnotation(ResponseMessageAnnotationKind.FilePath, default, fileId, index);
        }

        public static FileSearchCallResult FileSearchCallResult(string fileId = default, string text = default, string filename = default, IDictionary<string, BinaryData> attributes = default, float? score = default)
        {
            attributes ??= new ChangeTrackingDictionary<string, BinaryData>();

            return new FileSearchCallResult(
                fileId,
                text,
                filename,
                attributes,
                score,
                default);
        }

        public static ComputerCallAction ComputerCallAction(string kind = default)
        {
            return new InternalUnknownComputerAction(kind.ToComputerCallActionKind(), default);
        }

        public static ComputerCallSafetyCheck ComputerCallSafetyCheck(string id = default, string code = default, string message = default)
        {
            return new ComputerCallSafetyCheck(id, code, message, default);
        }

        public static McpToolDefinition McpToolDefinition(string name = default, string description = default, BinaryData inputSchema = default, BinaryData annotations = default)
        {
            return new McpToolDefinition(name, description, inputSchema, annotations, default);
        }

        public static ResponseConversationOptions ResponseConversationOptions(string conversationId = default)
        {
            return new ResponseConversationOptions(conversationId, default);
        }

        public static ResponseResult ResponseResult(IDictionary<string, string> metadata = default, float? temperature = default, int? topLogProbabilityCount = default, float? topP = default, string endUserId = default, string safetyIdentifier = default, ResponseServiceTier? serviceTier = default, string previousResponseId = default, string model = default, ResponseReasoningOptions reasoningOptions = default, bool? backgroundModeEnabled = default, int? maxOutputTokenCount = default, int? maxToolCallCount = default, string instructions = default, ResponseTextOptions textOptions = default, IEnumerable<ResponseTool> tools = default, ResponseToolChoice toolChoice = default, ResponseTruncationMode? truncationMode = default, string id = default, ResponseStatus? status = default, DateTimeOffset createdAt = default, ResponseError error = default, ResponseIncompleteStatusDetails incompleteStatusDetails = default, IEnumerable<ResponseItem> outputItems = default, ResponseTokenUsage usage = default, bool parallelToolCallsEnabled = default, ResponseConversationOptions conversationOptions = default)
        {
            metadata ??= new ChangeTrackingDictionary<string, string>();
            tools ??= new ChangeTrackingList<ResponseTool>();
            outputItems ??= new ChangeTrackingList<ResponseItem>();

            return new ResponseResult(
                metadata,
                temperature,
                topLogProbabilityCount,
                topP,
                endUserId,
                safetyIdentifier,
                serviceTier,
                previousResponseId,
                model,
                reasoningOptions,
                backgroundModeEnabled,
                maxOutputTokenCount,
                maxToolCallCount,
                instructions,
                textOptions,
                tools.ToList(),
                toolChoice,
                truncationMode,
                id,
                "response",
                status,
                createdAt,
                error,
                incompleteStatusDetails,
                outputItems.ToList(),
                usage,
                parallelToolCallsEnabled,
                conversationOptions,
                default);
        }

        public static ResponseError ResponseError(ResponseErrorCode code = default, string message = default)
        {
            return new ResponseError(code, message, default);
        }

        public static ResponseIncompleteStatusDetails ResponseIncompleteStatusDetails(ResponseIncompleteStatusReason? reason = default)
        {
            return new ResponseIncompleteStatusDetails(reason, default);
        }

        public static ResponseTokenUsage ResponseTokenUsage(int inputTokenCount = default, ResponseInputTokenUsageDetails inputTokenDetails = default, int outputTokenCount = default, ResponseOutputTokenUsageDetails outputTokenDetails = default, int totalTokenCount = default)
        {
            return new ResponseTokenUsage(
                inputTokenCount,
                inputTokenDetails,
                outputTokenCount,
                outputTokenDetails,
                totalTokenCount,
                default);
        }

        public static ResponseInputTokenUsageDetails ResponseInputTokenUsageDetails(int cachedTokenCount = default)
        {
            return new ResponseInputTokenUsageDetails(cachedTokenCount, default);
        }

        public static ResponseOutputTokenUsageDetails ResponseOutputTokenUsageDetails(int reasoningTokenCount = default)
        {
            return new ResponseOutputTokenUsageDetails(reasoningTokenCount, default);
        }

        public static ResponseDeletionResult ResponseDeletionResult(string responseId = default, bool deleted = default)
        {
            return new ResponseDeletionResult(responseId, "response.deleted", deleted, default);
        }

        public static ResponseItemCollectionPage ResponseItemCollectionPage(IEnumerable<ResponseItem> data = default, bool hasMore = default, string firstId = default, string lastId = default)
        {
            data ??= new ChangeTrackingList<ResponseItem>();

            return new ResponseItemCollectionPage(
                "list",
                data.ToList(),
                hasMore,
                firstId,
                lastId,
                default);
        }
        public static ResponseItemCollectionOptions ResponseItemCollectionOptions(string responseId = default, string afterId = default, string beforeId = default, int? pageSizeLimit = default, ResponseItemCollectionOrder? order = default)
        {
            return new ResponseItemCollectionOptions(
                responseId,
                afterId,
                beforeId,
                pageSizeLimit,
                order,
                additionalBinaryDataProperties: null);
        }

        public static GetResponseOptions GetResponseOptions(string responseId = default, int? startingAfter = default, bool? includeObfuscation = default, IEnumerable<IncludedResponseProperty> includedProperties = default, bool? streamingEnabled = default)
        {
            includedProperties ??= new ChangeTrackingList<IncludedResponseProperty>();

            return new GetResponseOptions(
                responseId,
                startingAfter,
                includeObfuscation,
                includedProperties.ToList(),
                streamingEnabled,
                default);
        }

        public static CustomMcpToolCallApprovalPolicy CustomMcpToolCallApprovalPolicy(McpToolFilter toolsAlwaysRequiringApproval = default, McpToolFilter toolsNeverRequiringApproval = default)
        {
            return new CustomMcpToolCallApprovalPolicy(toolsAlwaysRequiringApproval, toolsNeverRequiringApproval, default);
        }

        public static McpToolCallApprovalPolicy McpToolCallApprovalPolicy(GlobalMcpToolCallApprovalPolicy? globalPolicy = default, CustomMcpToolCallApprovalPolicy customPolicy = default)
        {
            return new McpToolCallApprovalPolicy(globalPolicy, customPolicy, default);
        }

        public static CodeInterpreterToolContainer CodeInterpreterToolContainer(string containerId = default, CodeInterpreterToolContainerConfiguration containerConfiguration = default)
        {
            return new CodeInterpreterToolContainer(containerId, containerConfiguration, default);
        }
    }
}
