using Microsoft.TypeSpec.Generator.Customizations;

namespace OpenAI.Assistants;

[CodeGenType("UnknownRunStepDetailsToolCallsCodeObjectCodeInterpreterOutputsObject")]
internal partial class UnknownRunStepDetailsToolCallsCodeObjectCodeInterpreterOutputsObject
{
}