//------------------------------------------------------------------------------
// <auto-generated>
//     This file is auto-generated by scripts/Export-Api.ps1 and must not be
//     modified manually. To update it, make the necessary source-code changes
//     and re-run scripts/Export-Api.ps1 to regenerate it.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OpenAI.Skills {
    public class SkillClient {
        protected SkillClient();
        public SkillClient(SkillClientSettings settings);
        public SkillClient(ApiKeyCredential credential, OpenAIClientOptions options);
        public SkillClient(ApiKeyCredential credential);
        public SkillClient(AuthenticationPolicy authenticationPolicy, OpenAIClientOptions options);
        public SkillClient(AuthenticationPolicy authenticationPolicy);
        protected internal SkillClient(ClientPipeline pipeline, OpenAIClientOptions options);
        public SkillClient(string apiKey);
        public Uri Endpoint { get; }
        public ClientPipeline Pipeline { get; }
        public virtual ClientResult DeleteSkill(string skillId, RequestOptions options = null);
        public virtual Task<ClientResult> DeleteSkillAsync(string skillId, RequestOptions options = null);
        public virtual ClientResult DeleteSkillVersion(string skillId, string version, RequestOptions options = null);
        public virtual Task<ClientResult> DeleteSkillVersionAsync(string skillId, string version, RequestOptions options = null);
        public virtual ClientResult DownloadSkill(string skillId, RequestOptions options = null);
        public virtual Task<ClientResult> DownloadSkillAsync(string skillId, RequestOptions options = null);
        public virtual ClientResult DownloadSkillVersion(string skillId, string version, RequestOptions options = null);
        public virtual Task<ClientResult> DownloadSkillVersionAsync(string skillId, string version, RequestOptions options = null);
        public virtual ClientResult GetSkill(string skillId, RequestOptions options = null);
        public virtual Task<ClientResult> GetSkillAsync(string skillId, RequestOptions options = null);
        public virtual ClientResult GetSkills(int? limit = null, string order = null, string after = null, RequestOptions options = null);
        public virtual Task<ClientResult> GetSkillsAsync(int? limit = null, string order = null, string after = null, RequestOptions options = null);
        public virtual ClientResult GetSkillVersion(string skillId, string version, RequestOptions options = null);
        public virtual Task<ClientResult> GetSkillVersionAsync(string skillId, string version, RequestOptions options = null);
        public virtual ClientResult GetSkillVersions(string skillId, int? limit = null, string order = null, string after = null, RequestOptions options = null);
        public virtual Task<ClientResult> GetSkillVersionsAsync(string skillId, int? limit = null, string order = null, string after = null, RequestOptions options = null);
        public virtual ClientResult UpdateSkill(string skillId, BinaryContent content, string contentType, RequestOptions options = null);
        public virtual Task<ClientResult> UpdateSkillAsync(string skillId, BinaryContent content, string contentType, RequestOptions options = null);
        public virtual ClientResult UploadSkill(BinaryContent content, string contentType, RequestOptions options = null);
        public virtual Task<ClientResult> UploadSkillAsync(BinaryContent content, string contentType, RequestOptions options = null);
        public virtual ClientResult UploadSkillVersion(string skillId, BinaryContent content, string contentType, RequestOptions options = null);
        public virtual Task<ClientResult> UploadSkillVersionAsync(string skillId, BinaryContent content, string contentType, RequestOptions options = null);
    }
    public sealed class SkillClientSettings : ClientSettings {
        public OpenAIClientOptions Options { get; set; }
        protected override void BindCore(Microsoft.Extensions.Configuration.IConfigurationSection section);
    }
}