//------------------------------------------------------------------------------
// <auto-generated>
//     This file is auto-generated by scripts/Export-Api.ps1 and must not be
//     modified manually. To update it, make the necessary source-code changes
//     and re-run scripts/Export-Api.ps1 to regenerate it.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OpenAI.Videos {
    public class VideoClient {
        protected VideoClient();
        public VideoClient(VideoClientSettings settings);
        public VideoClient(ApiKeyCredential credential, OpenAIClientOptions options);
        public VideoClient(ApiKeyCredential credential);
        public VideoClient(AuthenticationPolicy authenticationPolicy, OpenAIClientOptions options);
        public VideoClient(AuthenticationPolicy authenticationPolicy);
        protected internal VideoClient(ClientPipeline pipeline, OpenAIClientOptions options);
        public VideoClient(string apiKey);
        public Uri Endpoint { get; }
        public ClientPipeline Pipeline { get; }
        public virtual ClientResult CreateVideo(BinaryContent content, string contentType, RequestOptions options = null);
        public virtual Task<ClientResult> CreateVideoAsync(BinaryContent content, string contentType, RequestOptions options = null);
        public virtual ClientResult CreateVideoRemix(string videoId, BinaryContent content, string contentType, RequestOptions options = null);
        public virtual Task<ClientResult> CreateVideoRemixAsync(string videoId, BinaryContent content, string contentType, RequestOptions options = null);
        public virtual ClientResult DeleteVideo(string videoId, RequestOptions options = null);
        public virtual Task<ClientResult> DeleteVideoAsync(string videoId, RequestOptions options = null);
        public virtual ClientResult DownloadVideo(string videoId, string variant = null, RequestOptions options = null);
        public virtual Task<ClientResult> DownloadVideoAsync(string videoId, string variant = null, RequestOptions options = null);
        public virtual ClientResult GetVideo(string videoId, RequestOptions options = null);
        public virtual Task<ClientResult> GetVideoAsync(string videoId, RequestOptions options = null);
        public virtual CollectionResult GetVideos(int? limit = null, string order = null, string after = null, RequestOptions options = null);
        public virtual AsyncCollectionResult GetVideosAsync(int? limit = null, string order = null, string after = null, RequestOptions options = null);
    }
    public sealed class VideoClientSettings : ClientSettings {
        public OpenAIClientOptions Options { get; set; }
        protected override void BindCore(Microsoft.Extensions.Configuration.IConfigurationSection section);
    }
}