namespace OpenAI.Responses;

[CodeGenType("ResponsesResponseStreamEventResponseFileSearchCallInProgress")] internal partial class InternalResponsesResponseStreamEventResponseFileSearchCallInProgress { }
[CodeGenType("ResponsesResponseStreamEventResponseFileSearchCallSearching")] internal partial class InternalResponsesResponseStreamEventResponseFileSearchCallSearching { }
[CodeGenType("ResponsesResponseStreamEventResponseFileSearchCallCompleted")] internal partial class InternalResponsesResponseStreamEventResponseFileSearchCallCompleted { }
[CodeGenType("ResponsesResponseStreamEventResponseFunctionCallArgumentsDelta")] internal partial class InternalResponsesResponseStreamEventResponseFunctionCallArgumentsDelta { }
[CodeGenType("ResponsesResponseStreamEventResponseFunctionCallArgumentsDone")] internal partial class InternalResponsesResponseStreamEventResponseFunctionCallArgumentsDone { }
[CodeGenType("ResponsesResponseStreamEventResponseOutputItemAdded")] internal partial class InternalResponsesResponseStreamEventResponseOutputItemAdded { }
[CodeGenType("ResponsesResponseStreamEventResponseOutputItemDone")] internal partial class InternalResponsesResponseStreamEventResponseOutputItemDone { }
[CodeGenType("ResponsesResponseStreamEventResponseOutputTextDelta")] internal partial class InternalResponsesResponseStreamEventResponseOutputTextDelta { }
[CodeGenType("ResponsesResponseStreamEventResponseOutputTextDone")] internal partial class InternalResponsesResponseStreamEventResponseOutputTextDone { }
[CodeGenType("ResponsesResponseStreamEventResponseRefusalDelta")] internal partial class InternalResponsesResponseStreamEventResponseRefusalDelta { }
[CodeGenType("ResponsesResponseStreamEventResponseRefusalDone")] internal partial class InternalResponsesResponseStreamEventResponseRefusalDone { }
[CodeGenType("UnknownResponsesResponseStreamEvent")] internal partial class UnknownResponsesResponseStreamEvent { }
[CodeGenType("ResponsesResponseStreamEventResponseFailed")] internal partial class InternalResponsesResponseStreamEventResponseFailed { }
[CodeGenType("ResponsesResponseStreamEventResponseIncomplete")] internal partial class InternalResponsesResponseStreamEventResponseIncomplete { }
[CodeGenType("ResponsesResponseStreamEventResponseCompleted")] internal partial class InternalResponsesResponseStreamEventResponseCompleted { }
[CodeGenType("ResponsesResponseStreamEventResponseCreated")] internal partial class InternalResponsesResponseStreamEventResponseCreated { }
[CodeGenType("ResponsesResponseStreamEventResponseInProgress")] internal partial class InternalResponsesResponseStreamEventResponseInProgress { }
[CodeGenType("ResponsesResponseStreamEventResponseWebSearchCallCompleted")] internal partial class InternalResponsesResponseStreamEventResponseWebSearchCallCompleted { }
[CodeGenType("ResponsesResponseStreamEventResponseWebSearchCallInProgress")] internal partial class InternalResponsesResponseStreamEventResponseWebSearchCallInProgress { }
[CodeGenType("ResponsesResponseStreamEventResponseWebSearchCallSearching")] internal partial class InternalResponsesResponseStreamEventResponseWebSearchCallSearching { }
