namespace OpenAI.Assistants;

[CodeGenModel("MessageCreationOptionsRole")]
public enum MessageRole
{
    /// <summary>
    /// Indicates the message is sent by an actual user.
    /// </summary>
    [CodeGenMember("User")]
    User,

    /// <summary>
    /// Indicates the message was generated by the assistant.
    /// </summary>
    [CodeGenMember("Assistant")]
    Assistant,
}