import "./client/assistants.client.tsp";
import "./client/audio.client.tsp";
import "./client/batch.client.tsp";
import "./client/chat.client.tsp";
import "./client/containers.client.tsp";
import "./client/embeddings.client.tsp";
import "./client/files.client.tsp";
import "./client/fine-tuning.client.tsp";
import "./client/graders.client.tsp";
import "./client/images.client.tsp";
import "./client/messages.client.tsp";
import "./client/moderations.client.tsp";
import "./client/runs.client.tsp";
import "./client/threads.client.tsp";
import "./client/vector-stores.client.tsp";

import "./client/models/audio.models.tsp";
import "./client/models/common.models.tsp";
import "./client/models/responses.models.tsp";
import "./client/models/vector-stores.models.tsp";

import "./base/entrypoints/sdk.dotnet";
