namespace OpenAI.Administration;

[CodeGenType("AuditLogActorServiceAccount")] public partial class InternalAuditLogActorServiceAccount { }
[CodeGenType("AuditLogActorUser")] public partial class InternalAuditLogActorUser { }
[CodeGenType("AuditLogActorApiKey")] public partial class InternalAuditLogActorApiKey { }
[CodeGenType("AuditLogActorSession")] public partial class InternalAuditLogActorSession { }
[CodeGenType("AuditLogActor")] public partial class InternalAuditLogActor { }
[CodeGenType("AuditLog")] public partial class InternalAuditLog { }
[CodeGenType("ListAuditLogsResponse")] public partial class InternalListAuditLogsResponse { }
[CodeGenType("Invite")] public partial class InternalInvite { }
[CodeGenType("InviteListResponse")] public partial class InternalInviteListResponse { }
[CodeGenType("InviteRequest")] public partial class InternalInviteRequest { }
[CodeGenType("InviteDeleteResponse")] public partial class InternalInviteDeleteResponse { }
[CodeGenType("User")] public partial class InternalUser { }
[CodeGenType("UserListResponse")] public partial class InternalUserListResponse { }
[CodeGenType("UserRoleUpdateRequest")] public partial class InternalUserRoleUpdateRequest { }
[CodeGenType("UserDeleteResponse")] public partial class InternalUserDeleteResponse { }
[CodeGenType("Project")] public partial class InternalProject { }
[CodeGenType("ProjectListResponse")] public partial class InternalProjectListResponse { }
[CodeGenType("ProjectCreateRequest")] public partial class InternalProjectCreateRequest { }
[CodeGenType("ProjectUpdateRequest")] public partial class InternalProjectUpdateRequest { }
[CodeGenType("DefaultProjectErrorResponse")] public partial class InternalDefaultProjectErrorResponse { }
[CodeGenType("ProjectUser")] public partial class InternalProjectUser { }
[CodeGenType("ProjectUserListResponse")] public partial class InternalProjectUserListResponse { }
[CodeGenType("ProjectUserCreateRequest")] public partial class InternalProjectUserCreateRequest { }
[CodeGenType("ProjectUserUpdateRequest")] public partial class InternalProjectUserUpdateRequest { }
[CodeGenType("ProjectUserDeleteResponse")] public partial class InternalProjectUserDeleteResponse { }
[CodeGenType("ProjectServiceAccount")] public partial class InternalProjectServiceAccount { }
[CodeGenType("ProjectServiceAccountListResponse")] public partial class InternalProjectServiceAccountListResponse { }
[CodeGenType("ProjectServiceAccountCreateRequest")] public partial class InternalProjectServiceAccountCreateRequest { }
[CodeGenType("ProjectServiceAccountCreateResponse")] public partial class InternalProjectServiceAccountCreateResponse { }
[CodeGenType("ProjectServiceAccountApiKey")] public partial class InternalProjectServiceAccountApiKey { }
[CodeGenType("ProjectServiceAccountDeleteResponse")] public partial class InternalProjectServiceAccountDeleteResponse { }
[CodeGenType("ProjectApiKey")] public partial class InternalProjectApiKey { }
[CodeGenType("ProjectApiKeyListResponse")] public partial class InternalProjectApiKeyListResponse { }
[CodeGenType("ProjectApiKeyDeleteResponse")] public partial class InternalProjectApiKeyDeleteResponse { }
