// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using System.Diagnostics.CodeAnalysis;

namespace OpenAI.Responses
{
    public partial class StreamingResponseCreatedUpdate : StreamingResponseUpdate
    {
        internal StreamingResponseCreatedUpdate(int sequenceNumber, ResponseResult response) : base(InternalResponseStreamEventType.ResponseCreated, sequenceNumber)
        {
            Response = response;
        }

#pragma warning disable SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.
        internal StreamingResponseCreatedUpdate(InternalResponseStreamEventType kind, int sequenceNumber, in JsonPatch patch, ResponseResult response) : base(kind, sequenceNumber, patch)
        {
            Response = response;
        }
#pragma warning restore SCME0001 // Type is for evaluation purposes only and is subject to change or removal in future updates.

        public ResponseResult Response { get; }
    }
}
