name: Bug report
description: Report an issue or bug with this library
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: non_api
    attributes:
      label: Confirm this is not an issue with the underlying OpenAI API
      description: Issues with the underlying OpenAI API should be reported in our [Developer Community](https://community.openai.com/c/api/7)
      options:
        - label: This is an issue with the Python library
          required: true
  - type: checkboxes
    id: non_azure
    attributes:
      label: Confirm this is not an issue with Azure OpenAI
      description: Issues related to Azure OpenAI should be reported in the [Azure SDK repo](https://github.com/Azure/azure-sdk-for-net/issues)
      options:
        - label: This is not an issue with Azure OpenAI
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is, and any additional context.
      placeholder: Tell us what you see.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Fetch a '...'
        2. Update the '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: code-snippets
    attributes:
      label: Code snippets
      description: If applicable, add code snippets to help explain your problem.
      render: C#
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: winOS
    validations:
      required: true
  - type: input
    id: language-version
    attributes:
      label: .NET version
      placeholder: 
    validations:
      required: true
  - type: input
    id: lib-version
    attributes:
      label: Library version
      placeholder: 
    validations:
      required: true