// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using OpenAI;

namespace OpenAI.Internal
{
    internal partial class ResponseFormatJsonSchemaJsonSchema
    {
        private protected IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        public ResponseFormatJsonSchemaJsonSchema(string name)
        {
            Argument.AssertNotNull(name, nameof(name));

            Name = name;
        }

        internal ResponseFormatJsonSchemaJsonSchema(string description, string name, BinaryData schema, bool? strict, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            Description = description;
            Name = name;
            Schema = schema;
            Strict = strict;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        public string Description { get; set; }

        public string Name { get; set; }

        public bool? Strict { get; set; }

        public BinaryData Schema { get; set; }

        internal IDictionary<string, BinaryData> SerializedAdditionalRawData
        {
            get => _additionalBinaryDataProperties;
            set => _additionalBinaryDataProperties = value;
        }
    }
}
