namespace OpenAI.Assistants;

[CodeGenType("UnknownRunStepDetailsToolCallsCodeObjectCodeInterpreterOutputsObject")]
public partial class UnknownRunStepDetailsToolCallsCodeObjectCodeInterpreterOutputsObject
{
}