// <auto-generated/>

#nullable disable

using System;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.Text.Json;
using OpenAI;

namespace OpenAI.Realtime
{
    public partial class RealtimeUpdate : IJsonModel<RealtimeUpdate>
    {
        public static explicit operator RealtimeUpdate(ClientResult result)
        {
            using PipelineResponse response = result.GetRawResponse();
            using JsonDocument document = JsonDocument.Parse(response.Content);
            return DeserializeRealtimeUpdate(document.RootElement, ModelSerializationExtensions.WireOptions);
        }
    }
}
