// <auto-generated/>

#nullable disable

using System;

namespace OpenAI.Files
{
    internal static partial class FilePurposeExtensions
    {
        public static string ToSerialString(this FilePurpose value) => value switch
        {
            FilePurpose.Assistants => "assistants",
            FilePurpose.AssistantsOutput => "assistants_output",
            FilePurpose.Batch => "batch",
            FilePurpose.BatchOutput => "batch_output",
            FilePurpose.FineTune => "fine-tune",
            FilePurpose.FineTuneResults => "fine-tune-results",
            FilePurpose.Vision => "vision",
            FilePurpose.UserData => "user_data",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown FilePurpose value.")
        };
    }
}
