<#
.SYNOPSIS
    Generates the public API surface for the OpenAI .NET library using GenAPI.

.DESCRIPTION
    This script invokes the MSBuild GenerateApi target to produce C# source files
    representing the public API contract of the OpenAI library. GenAPI writes one
    intermediate file per target framework, and this script splits those files by
    namespace into target framework subdirectories under the 'api/wip' folder at
    the repository root.

.EXAMPLE
    .\Export-Api.ps1
    Generates API for all target frameworks defined in
    ClientTargetFrameworks (Directory.Build.props) using the Release configuration.

.NOTES
    Outputs are written to api/wip/<TargetFramework>/<Namespace>.<TargetFramework>.cs
#>

[CmdletBinding()]
param(
)

$ErrorActionPreference = "Stop"

# ── Function Definitions ──────────────────────────────────────────────────────

# Returns the auto-generated header prepended to every API listing file.
function Get-GeneratedHeader {
    return @"
//------------------------------------------------------------------------------
// <auto-generated>
//     This file is auto-generated by scripts/Export-Api.ps1 and must not be
//     modified manually. To update it, make the necessary source-code changes
//     and re-run scripts/Export-Api.ps1 to regenerate it.
// </auto-generated>
//------------------------------------------------------------------------------
"@
}

# Cleans and normalizes raw GenAPI output into a compact, public-only API listing.
# Strips fully-qualified namespace prefixes, internal/private members, and
# implementation details such as IJsonModel/IPersistableModel methods. Within each
# OpenAI sub-namespace block, the block's own namespace prefix is removed for
# brevity while cross-namespace references are preserved.
function Format-ApiListing {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Content
    )

    $generatedHeader = Get-GeneratedHeader

    # Replace the generic auto-generated header with one that explicitly names this script.
    $Content = $Content -creplace '(?s)^//[-]+.*?//[-]+\r?\n', ($generatedHeader + "`n")

    # Normalize line breaks and whitespace.
    $Content = $Content -creplace '\r?\n\r?\n', "`n"
    $Content = $Content -creplace '\r?\n *{', " {"

    # Remove fully-qualified namespace prefixes.
    @(
        "Diagnostics\.CodeAnalysis\.",
        "System\.ComponentModel\.",
        "System\.ClientModel\.Primitives\.",
        "System\.ClientModel\.",
        "System\.Collections\.Generic\.",
        "System\.Collections\.",
        "System\.Threading\.Tasks\.",
        "System\.Threading\.",
        "System\.Text\.Json\.",
        "System\.Text\.",
        "System\.IO\.",
        "System\." # System must be last to avoid partial matches
    ) | ForEach-Object { $Content = $Content -creplace $_, "" }

    # Remove OpenAI sub-namespace prefixes within their own namespace blocks for a more compact view.
    # Each namespace block only has its own prefix stripped (e.g. "OpenAI.Containers." is removed
    # inside the OpenAI.Containers block, but "OpenAI.Chat." references there remain unchanged).
    $namespaceBlockPattern = '(?ms)^(namespace (?<NS>OpenAI\.[A-Za-z0-9_]+) \{.*?(?=^namespace OpenAI(?:\.[A-Za-z0-9_]+)* \{|\z))'
    $Content = [regex]::Replace($Content, $namespaceBlockPattern, {
        param($m)
        $ns = $m.Groups["NS"].Value
        $block = $m.Value
        $block = $block -creplace "$([regex]::Escape($ns))\.", ""
        return $block
    })

    # Remove non-public APIs.
    $Content = $Content -creplace "  * internal.*`n", ""
    $Content = $Content -creplace ".*private.*dummy.*`n", ""

    # Remove Diagnostics.DebuggerStepThrough attribute.
    $Content = $Content -creplace ".*Diagnostics.DebuggerStepThrough.*\n", ""

    # Remove ModelReaderWriterBuildable attributes.
    $Content = $Content -creplace '\[ModelReaderWriterBuildable\(typeof\([^\)]+\)\)\]\s*', ''

    # Remove IJsonModel/IPersistableModel interface method entries.
    $Content = $Content -creplace "        .*(IJsonModel|IPersistableModel).*`n", ""

    # Remove JsonModelCreateCore, JsonModelWriteCore, PersistableModelCreateCore, PersistableModelWriteCore methods,
    # including any attribute lines (e.g. [Experimental(...)]) that immediately precede them.
    $Content = $Content -creplace "(?:        \[[^\n]+\]\r?\n)*        protected (?:virtual|override) [^\n]*(JsonModelCreateCore|JsonModelWriteCore|PersistableModelCreateCore|PersistableModelWriteCore)[^\n]*\r?\n", ""

    # Other cosmetic simplifications.
    $Content = $Content -creplace "partial class", "class"
    $Content = $Content -creplace " { throw null; }", ";"
    $Content = $Content -creplace " { }", ";"

    return $Content
}

# Splits a formatted monolithic API listing into one file per namespace.
# Writes each namespace block to <OutputDirectory>/<TargetFramework>/<Namespace>.<TargetFramework>.cs.
function Split-Artifact {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Content,

        [Parameter(Mandatory = $true)]
        [string]$TargetFramework,

        [Parameter(Mandatory = $true)]
        [string]$ProjectName,

        [Parameter(Mandatory = $true)]
        [string]$OutputDirectory
    )

    $generatedHeader = Get-GeneratedHeader
    $targetFrameworkDirectory = Join-Path $OutputDirectory $TargetFramework

    New-Item -ItemType Directory -Path $targetFrameworkDirectory -Force | Out-Null
    Get-ChildItem -Path $targetFrameworkDirectory -Filter "$ProjectName*.$TargetFramework.cs" -Force | Remove-Item -Force

    $body = $Content -creplace "(?s)^$([regex]::Escape($generatedHeader))\r?\n", ""
    $namespaceMatches = [regex]::Matches($body, '(?ms)^namespace (?<Namespace>OpenAI(?:\.[A-Za-z0-9_]+)*) \{.*?(?=^namespace OpenAI(?:\.[A-Za-z0-9_]+)* \{|\z)')

    if ($namespaceMatches.Count -eq 0) {
        throw "No namespace declarations were found for $ProjectName $TargetFramework."
    }

    foreach ($match in $namespaceMatches) {
        $namespace = $match.Groups["Namespace"].Value
        $fileName = "$namespace.$TargetFramework.cs"
        $filePath = Join-Path $targetFrameworkDirectory $fileName
        $fileContent = $generatedHeader + "`n" + $match.Value.Trim()

        Set-Content -Path $filePath -Value $fileContent -NoNewline
        Write-Host "  Wrote $TargetFramework/$fileName"
    }
}

# ── Main Script ───────────────────────────────────────────────────────────────

$configuration = "Release"

# Resolve paths
$repoRootPath = Join-Path $PSScriptRoot ".." -Resolve
$outputDirectory = Join-Path $repoRootPath "api" "wip"
$intermediateDirectory = Join-Path $repoRootPath "artifacts" "api"

# Projects to export. Each entry has a project file path and the library name
# used as the prefix for the generated API files.
$projects = @(
    @{
        Name = "OpenAI"
        Path = Join-Path $repoRootPath "OpenAI" "src" "OpenAI.csproj"
    }
)

# Get ClientTargetFrameworks from Directory.Build.props
$propsPath = Join-Path $repoRootPath "Directory.Build.props"
$clientTargetFrameworks = ""
if (Test-Path $propsPath) {
    $propsContent = Get-Content $propsPath -Raw
    if ($propsContent -match '<ClientTargetFrameworks>([^<]+)</ClientTargetFrameworks>') {
        $clientTargetFrameworks = $Matches[1]
    }
}

if (-not $clientTargetFrameworks) {
    Write-Error "Could not find ClientTargetFrameworks in Directory.Build.props"
    exit 1
}

$targetFrameworks = $clientTargetFrameworks -split ';' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }

Write-Host ""
Write-Host "Target Frameworks: $clientTargetFrameworks" -ForegroundColor Green
Write-Host "Configuration: $configuration"
Write-Host ""

# Ensure output directories exist and are clean (only remove generated .cs files, not other files like README.md)
if (Test-Path $outputDirectory) {
    Write-Host "Cleaning existing output directory..." -ForegroundColor Cyan
    try {
        foreach ($project in $projects) {
            foreach ($targetFramework in $targetFrameworks) {
                $targetFrameworkDirectory = Join-Path $outputDirectory $targetFramework
                if (Test-Path $targetFrameworkDirectory) {
                    Get-ChildItem -Path $targetFrameworkDirectory -Filter "$($project.Name)*.$targetFramework.cs" -Force | Remove-Item -Force
                }
                else {
                    New-Item -ItemType Directory -Path $targetFrameworkDirectory -Force | Out-Null
                }
            }
        }
    }
    catch {
        Write-Warning "Failed to clean some items in output directory: $_"
    }
} else {
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
    Write-Host "Created output directory: $outputDirectory"
}

if (Test-Path $intermediateDirectory) {
    Remove-Item -Path $intermediateDirectory -Recurse -Force
}
New-Item -ItemType Directory -Path $intermediateDirectory -Force | Out-Null

Write-Host "Output Directory: $outputDirectory"
Write-Host "Intermediate Directory: $intermediateDirectory"
Write-Host ""

foreach ($project in $projects) {
    $projectName = $project.Name
    $projectPath = $project.Path

    Write-Host "================================================================" -ForegroundColor Cyan
    Write-Host "Running GenAPI for $projectName..." -ForegroundColor Cyan
    Write-Host "================================================================" -ForegroundColor Cyan
    Write-Host ""

    # Build the dotnet command arguments
    $buildArgs = @(
        "build"
        $projectPath
        "-t:ExportApi"
        "-c:$configuration"
        "-p:ExportingApi=true"
        "-m"
    )

    # Run a single build command - the MSBuild target handles all frameworks
    & dotnet @buildArgs
    if ($LASTEXITCODE -ne 0) {
        Write-Error "GenAPI failed for $projectName with exit code $LASTEXITCODE"
        exit $LASTEXITCODE
    }

    Write-Host ""
    Write-Host "Cleaning and splitting generated files for $projectName..." -ForegroundColor Cyan

    foreach ($targetFramework in $targetFrameworks) {
        $generatedFile = Join-Path $intermediateDirectory "$projectName.$targetFramework.cs"

        if (-not (Test-Path $generatedFile)) {
            throw "Expected generated API file was not found: $generatedFile"
        }

        Write-Host "  Processing $projectName.$targetFramework.cs..."

        $content = Get-Content $generatedFile -Raw
        $content = Format-ApiListing -Content $content
        Split-Artifact -Content $content -TargetFramework $targetFramework -ProjectName $projectName -OutputDirectory $outputDirectory
        Remove-Item -Path $generatedFile -Force
    }

    Write-Host ""
}

if (Test-Path $intermediateDirectory) {
    Remove-Item -Path $intermediateDirectory -Recurse -Force
}

Write-Host "API generation completed successfully." -ForegroundColor Green
Write-Host ""

# List generated files
Write-Host "Generated files:" -ForegroundColor Cyan
foreach ($project in $projects) {
    foreach ($targetFramework in $targetFrameworks) {
        $targetFrameworkDirectory = Join-Path $outputDirectory $targetFramework
        Get-ChildItem -Path $targetFrameworkDirectory -Filter "$($project.Name)*.$targetFramework.cs" | Sort-Object Name | ForEach-Object {
            Write-Host "  - $targetFramework/$($_.Name)"
        }
    }
}
Write-Host ""
