<#
.SYNOPSIS
    Generates the public API surface for the OpenAI .NET library using GenAPI.

.DESCRIPTION
    By default, this script invokes the MSBuild GenerateApi target to produce C#
    source files representing the current public API contract of the OpenAI
    library. In released mode, it downloads the package version recorded in
    api/api-version.txt and generates listings from the package assemblies.

.PARAMETER Released
    Generates api/released from the published OpenAI package instead of generating
    api/in-progress from the current source tree.

.EXAMPLE
    .\Export-Api.ps1
    Generates API for all target frameworks defined in
    ClientTargetFrameworks (Directory.Build.props) using the Release configuration.

.EXAMPLE
    .\Export-Api.ps1 -Released
    Generates released API listings from the published package version recorded in
    api/api-version.txt.

.NOTES
    Current-source outputs are written to
    api/in-progress/<TargetFramework>/<Namespace>.<TargetFramework>.cs.
    Released-package outputs are written to the equivalent api/released path.
#>

[CmdletBinding()]
param(
    [Parameter()]
    [switch]$Released
)

$ErrorActionPreference = "Stop"

# ── Function Definitions ──────────────────────────────────────────────────────

# Returns the auto-generated header prepended to every API listing file.
function Get-GeneratedHeader {
    param(
        [Parameter()]
        [switch]$Released
    )

    if ($Released) {
        return @"
//------------------------------------------------------------------------------
// <auto-generated>
//     This file is auto-generated from the published OpenAI package by
//     scripts/Export-Api.ps1 and must not be modified manually. To update it,
//     update api/api-version.txt and run scripts/Export-Api.ps1 -Released.
// </auto-generated>
//------------------------------------------------------------------------------
"@
    }

    return @"
//------------------------------------------------------------------------------
// <auto-generated>
//     This file is auto-generated by scripts/Export-Api.ps1 and must not be
//     modified manually. To update it, make the necessary source-code changes
//     and re-run scripts/Export-Api.ps1 to regenerate it.
// </auto-generated>
//------------------------------------------------------------------------------
"@
}

# Cleans and normalizes raw GenAPI output into a compact, public-only API listing.
# Strips fully-qualified namespace prefixes, internal/private members, and
# implementation details such as IJsonModel/IPersistableModel methods. Within each
# OpenAI sub-namespace block, the block's own namespace prefix is removed for
# brevity while cross-namespace references are preserved.
function Format-ApiListing {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Content,

        [Parameter(Mandatory = $true)]
        [string]$GeneratedHeader
    )

    # Replace the generic auto-generated header with one that explicitly names this script.
    $Content = $Content -creplace '(?s)^//[-]+.*?//[-]+\r?\n', ($GeneratedHeader + "`n")

    # Normalize line breaks and whitespace.
    $Content = $Content -creplace '\r?\n\r?\n', "`n"
    $Content = $Content -creplace '\r?\n *{', " {"

    # Remove fully-qualified namespace prefixes.
    @(
        "Diagnostics\.CodeAnalysis\.",
        "System\.ComponentModel\.",
        "System\.ClientModel\.Primitives\.",
        "System\.ClientModel\.",
        "System\.Collections\.Generic\.",
        "System\.Collections\.",
        "System\.Threading\.Tasks\.",
        "System\.Threading\.",
        "System\.Text\.Json\.",
        "System\.Text\.",
        "System\.IO\.",
        "System\." # System must be last to avoid partial matches
    ) | ForEach-Object { $Content = $Content -creplace $_, "" }

    # Remove OpenAI sub-namespace prefixes within their own namespace blocks for a more compact view.
    # Each namespace block only has its own prefix stripped (e.g. "OpenAI.Containers." is removed
    # inside the OpenAI.Containers block, but "OpenAI.Chat." references there remain unchanged).
    $namespaceBlockPattern = '(?ms)^(namespace (?<NS>OpenAI\.[A-Za-z0-9_]+) \{.*?(?=^namespace OpenAI(?:\.[A-Za-z0-9_]+)* \{|\z))'
    $Content = [regex]::Replace($Content, $namespaceBlockPattern, {
        param($m)
        $ns = $m.Groups["NS"].Value
        $block = $m.Value
        $block = $block -creplace "$([regex]::Escape($ns))\.", ""
        return $block
    })

    # Remove non-public APIs.
    $Content = $Content -creplace "  * internal.*`n", ""
    $Content = $Content -creplace ".*private.*dummy.*`n", ""

    # Remove Diagnostics.DebuggerStepThrough attribute.
    $Content = $Content -creplace ".*Diagnostics.DebuggerStepThrough.*\n", ""

    # Remove ModelReaderWriterBuildable attributes.
    $Content = $Content -creplace '\[ModelReaderWriterBuildable\(typeof\([^\)]+\)\)\]\s*', ''

    # Remove IJsonModel/IPersistableModel interface method entries.
    $Content = $Content -creplace "        .*(IJsonModel|IPersistableModel).*`n", ""

    # Remove JsonModelCreateCore, JsonModelWriteCore, PersistableModelCreateCore, PersistableModelWriteCore methods,
    # including any attribute lines (e.g. [Experimental(...)]) that immediately precede them.
    $Content = $Content -creplace "(?:        \[[^\n]+\]\r?\n)*        protected (?:virtual|override) [^\n]*(JsonModelCreateCore|JsonModelWriteCore|PersistableModelCreateCore|PersistableModelWriteCore)[^\n]*\r?\n", ""

    # Other cosmetic simplifications.
    $Content = $Content -creplace "partial class", "class"
    $Content = $Content -creplace " { throw null; }", ";"
    $Content = $Content -creplace " { }", ";"

    return $Content
}

# Splits a formatted monolithic API listing into one file per namespace.
# Writes each namespace block to <OutputDirectory>/<TargetFramework>/<Namespace>.<TargetFramework>.cs.
function Split-Artifact {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Content,

        [Parameter(Mandatory = $true)]
        [string]$TargetFramework,

        [Parameter(Mandatory = $true)]
        [string]$ProjectName,

        [Parameter(Mandatory = $true)]
        [string]$OutputDirectory,

        [Parameter(Mandatory = $true)]
        [string]$GeneratedHeader
    )

    $targetFrameworkDirectory = Join-Path $OutputDirectory $TargetFramework

    New-Item -ItemType Directory -Path $targetFrameworkDirectory -Force | Out-Null
    Get-ChildItem -Path $targetFrameworkDirectory -Filter "$ProjectName*.$TargetFramework.cs" -Force | Remove-Item -Force

    $body = $Content -creplace "(?s)^$([regex]::Escape($GeneratedHeader))\r?\n", ""
    $namespaceMatches = [regex]::Matches($body, '(?ms)^namespace (?<Namespace>OpenAI(?:\.[A-Za-z0-9_]+)*) \{.*?(?=^namespace OpenAI(?:\.[A-Za-z0-9_]+)* \{|\z)')

    if ($namespaceMatches.Count -eq 0) {
        throw "No namespace declarations were found for $ProjectName $TargetFramework."
    }

    foreach ($match in $namespaceMatches) {
        $namespace = $match.Groups["Namespace"].Value
        $fileName = "$namespace.$TargetFramework.cs"
        $filePath = Join-Path $targetFrameworkDirectory $fileName
        $fileContent = $GeneratedHeader + "`n" + $match.Value.Trim()

        Set-Content -Path $filePath -Value $fileContent -NoNewline
        Write-Host "  Wrote $TargetFramework/$fileName"
    }
}

function Invoke-DotNetCommand {
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$Arguments,

        [Parameter()]
        [string]$WorkingDirectory
    )

    # Use ArgumentList instead of building a single command string. This lets .NET
    # quote each path correctly on Windows and Unix, including paths with spaces
    # such as "C:\Program Files\dotnet\...". Redirecting both streams also lets
    # callers parse machine-readable stdout while retaining stderr diagnostics.
    $startInfo = [System.Diagnostics.ProcessStartInfo]::new()
    $startInfo.FileName = "dotnet"
    $startInfo.UseShellExecute = $false
    $startInfo.RedirectStandardOutput = $true
    $startInfo.RedirectStandardError = $true
    if ($WorkingDirectory) {
        $startInfo.WorkingDirectory = $WorkingDirectory
    }

    foreach ($argument in $Arguments) {
        $startInfo.ArgumentList.Add($argument)
    }

    $process = [System.Diagnostics.Process]::new()
    $process.StartInfo = $startInfo

    try {
        if (-not $process.Start()) {
            throw "Failed to start dotnet $($Arguments -join ' ')."
        }

        # Read stdout and stderr concurrently. Reading one stream to completion
        # before the other can deadlock when a child process fills the unread
        # stream's operating-system buffer.
        $standardOutputTask = $process.StandardOutput.ReadToEndAsync()
        $standardErrorTask = $process.StandardError.ReadToEndAsync()
        $process.WaitForExit()

        $standardOutput = $standardOutputTask.GetAwaiter().GetResult()
        $standardError = $standardErrorTask.GetAwaiter().GetResult()
        $exitCode = $process.ExitCode
    }
    finally {
        $process.Dispose()
    }

    if ($exitCode -ne 0) {
        $details = @($standardOutput.Trim(), $standardError.Trim()) | Where-Object { $_ } | Join-String -Separator ([Environment]::NewLine)
        throw "dotnet $($Arguments -join ' ') failed with exit code $exitCode.$([Environment]::NewLine)$details"
    }

    return [pscustomobject]@{
        StandardOutput = $standardOutput
        StandardError = $standardError
    }
}

function Invoke-ReleasedApiExport {
    param(
        [Parameter(Mandatory = $true)]
        [string]$RepositoryRoot
    )

    $versionPath = Join-Path $RepositoryRoot "api" "api-version.txt"
    $toolManifestPath = Join-Path $RepositoryRoot ".config" "dotnet-tools.json"
    $packagesPropsPath = Join-Path $RepositoryRoot "Directory.Packages.props"
    $nugetConfigPath = Join-Path $RepositoryRoot "nuget.config"
    $resolverProjectPath = Join-Path $RepositoryRoot "scripts" "ApiExport" "ReleasedApiReferenceResolver.csproj"
    $outputDirectory = Join-Path $RepositoryRoot "api" "released"

    if (-not (Test-Path $versionPath -PathType Leaf)) {
        throw "API version file was not found: $versionPath"
    }

    $apiVersion = (Get-Content $versionPath -Raw).Trim()
    if ($apiVersion -notmatch '^\d+\.\d+\.\d+(?:-[0-9A-Za-z]+(?:[.-][0-9A-Za-z]+)*)?$') {
        throw "API version '$apiVersion' is not a valid package version."
    }

    # Current-source export uses Microsoft.DotNet.GenAPI.Task while released
    # export uses Microsoft.DotNet.GenAPI.Tool. Both packages call the same GenAPI
    # implementation only when their versions match, so reject version drift
    # rather than silently producing differently rendered baselines.
    $toolManifest = Get-Content $toolManifestPath -Raw | ConvertFrom-Json
    $genApiTool = $toolManifest.tools.'microsoft.dotnet.genapi.tool'
    if (-not $genApiTool -or [string]::IsNullOrWhiteSpace($genApiTool.version)) {
        throw "Microsoft.DotNet.GenAPI.Tool was not found in $toolManifestPath."
    }

    [xml]$packagesProps = Get-Content $packagesPropsPath -Raw
    $genApiTaskVersions = @(
        $packagesProps.Project.ItemGroup.PackageVersion |
            Where-Object { $_.Include -eq "Microsoft.DotNet.GenAPI.Task" } |
            ForEach-Object { $_.Version }
    )
    if ($genApiTaskVersions.Count -ne 1) {
        throw "Expected exactly one Microsoft.DotNet.GenAPI.Task version in $packagesPropsPath."
    }
    if ($genApiTool.version -ne $genApiTaskVersions[0]) {
        throw "GenAPI tool version '$($genApiTool.version)' must match task version '$($genApiTaskVersions[0])'."
    }

    Write-Host "Restoring Microsoft.DotNet.GenAPI.Tool $($genApiTool.version)..." -ForegroundColor Cyan
    $toolRestore = Invoke-DotNetCommand -Arguments @(
        "tool", "restore",
        "--tool-manifest", $toolManifestPath,
        "--configfile", $nugetConfigPath
    )
    if ($toolRestore.StandardOutput) {
        Write-Host $toolRestore.StandardOutput.Trim()
    }

    # Keep every download, restore, and generated intermediate under one unique
    # ignored directory. For example, concurrent runs use different paths such as
    # artifacts/api/released-a1b2... and cannot delete each other's state.
    $invocationId = [guid]::NewGuid().ToString("N")
    $workRoot = Join-Path $RepositoryRoot "artifacts" "api" "released-$invocationId"
    $downloadDirectory = Join-Path $workRoot "download"
    $extractedDirectory = Join-Path $workRoot "extracted"
    $packagesDirectory = Join-Path $workRoot "packages"
    $objDirectory = Join-Path $workRoot "obj"
    $rawDirectory = Join-Path $workRoot "raw"
    $formattedDirectory = Join-Path $workRoot "formatted"
    $backupDirectory = Join-Path (Split-Path $outputDirectory -Parent) "released-backup-$invocationId"
    $releasedHeader = Get-GeneratedHeader -Released

    try {
        @($downloadDirectory, $extractedDirectory, $packagesDirectory, $objDirectory, $rawDirectory, $formattedDirectory) |
            ForEach-Object { New-Item -ItemType Directory -Path $_ -Force | Out-Null }

        # NuGet's flat-container IDs and versions are normalized to lowercase.
        # The SemVer 2 registration leaf supplies both the canonical package URL
        # and a catalog record containing NuGet's SHA-512 package hash. Following
        # that chain verifies that the bytes are the package NuGet registered;
        # validating the extracted .nuspec below independently verifies identity.
        $normalizedVersion = $apiVersion.ToLowerInvariant()
        $packageBaseUrl = "https://api.nuget.org/v3-flatcontainer/openai/$normalizedVersion/openai.$normalizedVersion.nupkg"
        $registrationUrl = "https://api.nuget.org/v3/registration5-gz-semver2/openai/$normalizedVersion.json"
        $packagePath = Join-Path $downloadDirectory "OpenAI.$apiVersion.nupkg"

        Write-Host "Downloading OpenAI $apiVersion from NuGet.org..." -ForegroundColor Cyan
        $registration = Invoke-RestMethod -Uri $registrationUrl
        if ($registration.packageContent -ne $packageBaseUrl -or [string]::IsNullOrWhiteSpace($registration.catalogEntry)) {
            throw "NuGet registration metadata for OpenAI $apiVersion was invalid."
        }
        $catalogEntry = Invoke-RestMethod -Uri $registration.catalogEntry
        if ($catalogEntry.id -cne "OpenAI" -or $catalogEntry.version -ne $apiVersion -or
            $catalogEntry.packageHashAlgorithm -cne "SHA512" -or [string]::IsNullOrWhiteSpace($catalogEntry.packageHash)) {
            throw "NuGet catalog metadata for OpenAI $apiVersion was invalid."
        }

        Invoke-RestMethod -Uri $registration.packageContent -OutFile $packagePath
        if (-not (Test-Path $packagePath -PathType Leaf) -or (Get-Item $packagePath).Length -eq 0) {
            throw "Downloaded package is missing or empty: $packageBaseUrl"
        }

        try {
            $expectedHash = [BitConverter]::ToString([Convert]::FromBase64String($catalogEntry.packageHash)).Replace("-", "")
        }
        catch {
            throw "NuGet catalog metadata contained an invalid SHA-512 value for OpenAI $apiVersion."
        }
        $actualHash = (Get-FileHash $packagePath -Algorithm SHA512).Hash
        if ($actualHash -ne $expectedHash) {
            throw "SHA-512 verification failed for $packagePath."
        }

        [System.IO.Compression.ZipFile]::ExtractToDirectory($packagePath, $extractedDirectory)

        $nuspecFiles = @(Get-ChildItem $extractedDirectory -Filter "*.nuspec" -File)
        if ($nuspecFiles.Count -ne 1) {
            throw "Expected exactly one root .nuspec in $packagePath."
        }

        [xml]$nuspec = Get-Content $nuspecFiles[0].FullName -Raw
        $packageId = $nuspec.SelectSingleNode("/*[local-name()='package']/*[local-name()='metadata']/*[local-name()='id']").InnerText
        $packageVersion = $nuspec.SelectSingleNode("/*[local-name()='package']/*[local-name()='metadata']/*[local-name()='version']").InnerText
        if ($packageId -cne "OpenAI" -or $packageVersion -ne $apiVersion) {
            throw "Downloaded package identity '$packageId $packageVersion' does not match 'OpenAI $apiVersion'."
        }

        # The package defines the released framework set. For example,
        # lib/net8.0/OpenAI.dll produces net8.0 listings. Do not use today's
        # ClientTargetFrameworks or NuGet nearest-framework selection because an
        # older package may have shipped a different set of exact assets.
        $libDirectory = Join-Path $extractedDirectory "lib"
        $packageAssemblies = @(
            Get-ChildItem $libDirectory -Directory |
                ForEach-Object {
                    $assemblyPath = Join-Path $_.FullName "OpenAI.dll"
                    if (Test-Path $assemblyPath -PathType Leaf) {
                        [pscustomobject]@{ TargetFramework = $_.Name; AssemblyPath = $assemblyPath }
                    }
                } |
                Sort-Object TargetFramework
        )
        if ($packageAssemblies.Count -eq 0) {
            throw "No lib/<tfm>/OpenAI.dll assets were found in OpenAI $apiVersion."
        }
        $duplicateFrameworks = @($packageAssemblies | Group-Object TargetFramework | Where-Object Count -gt 1)
        if ($duplicateFrameworks.Count -gt 0) {
            throw "Duplicate target framework assets were found: $($duplicateFrameworks.Name -join ', ')."
        }

        Write-Host "Released package frameworks: $($packageAssemblies.TargetFramework -join ';')" -ForegroundColor Green

        foreach ($packageAssembly in $packageAssemblies) {
            $targetFramework = $packageAssembly.TargetFramework
            $targetObjDirectory = Join-Path $objDirectory $targetFramework
            New-Item -ItemType Directory -Path $targetObjDirectory -Force | Out-Null

            # GenAPI needs the same compile-time closure a compiler would use,
            # including framework reference assemblies and transitive packages.
            # The tiny resolver project lets NuGet/MSBuild make those selections.
            # `-getItem:ReferencePath` returns JSON shaped approximately as:
            # { "Items": { "ReferencePath": [
            #   { "FullPath": ".../System.ClientModel.dll",
            #     "NuGetPackageId": "System.ClientModel" }
            # ] } }
            # Terminal logging is disabled so progress/ANSI output cannot corrupt
            # the JSON read from stdout.
            Write-Host "Resolving references for $targetFramework..." -ForegroundColor Cyan
            $referenceQuery = Invoke-DotNetCommand -Arguments @(
                "msbuild", $resolverProjectPath,
                "-restore",
                "-target:ResolveReferences",
                "-property:ReleasedApiVersion=$apiVersion",
                "-property:ReleasedApiTargetFramework=$targetFramework",
                "-property:RestorePackagesPath=$packagesDirectory",
                "-property:BaseIntermediateOutputPath=$targetObjDirectory$([IO.Path]::DirectorySeparatorChar)",
                "-property:MSBuildProjectExtensionsPath=$targetObjDirectory$([IO.Path]::DirectorySeparatorChar)",
                "-property:RestoreConfigFile=$nugetConfigPath",
                "-getItem:ReferencePath",
                "-nologo",
                "-verbosity:quiet",
                "-terminalLogger:off"
            )

            try {
                $queryResult = $referenceQuery.StandardOutput | ConvertFrom-Json -Depth 100
            }
            catch {
                throw "MSBuild returned invalid reference query JSON for $targetFramework.$([Environment]::NewLine)$($referenceQuery.StandardOutput)"
            }

            $referenceItems = @($queryResult.Items.ReferencePath)
            if ($referenceItems.Count -eq 0) {
                throw "MSBuild returned no ReferencePath items for $targetFramework."
            }

            $resolvedReferences = foreach ($referenceItem in $referenceItems) {
                $referencePath = if ($referenceItem.FullPath) { $referenceItem.FullPath } else { $referenceItem.Identity }
                if (-not [IO.Path]::IsPathRooted($referencePath)) {
                    $referencePath = [IO.Path]::GetFullPath((Join-Path (Split-Path $resolverProjectPath -Parent) $referencePath))
                }
                if (-not (Test-Path $referencePath -PathType Leaf)) {
                    throw "Resolved reference was not found for ${targetFramework}: $referencePath"
                }

                [pscustomobject]@{
                    Path = $referencePath
                    NuGetPackageId = $referenceItem.NuGetPackageId
                }
            }

            # The restore is performed only to resolve references; the explicitly
            # downloaded archive remains the API authority. Matching hashes proves
            # NuGet selected the same OpenAI asset, after which that restored copy
            # is removed from --assembly-reference to avoid loading it twice.
            $resolvedPackageAssemblies = @(
                $resolvedReferences |
                    Where-Object { $_.NuGetPackageId -eq "OpenAI" -and [IO.Path]::GetFileName($_.Path) -eq "OpenAI.dll" }
            )
            if ($resolvedPackageAssemblies.Count -ne 1) {
                throw "Expected exactly one restored OpenAI.dll for $targetFramework but found $($resolvedPackageAssemblies.Count)."
            }
            if ((Get-FileHash $resolvedPackageAssemblies[0].Path -Algorithm SHA256).Hash -ne
                (Get-FileHash $packageAssembly.AssemblyPath -Algorithm SHA256).Hash) {
                throw "Restored OpenAI.dll does not match the downloaded package asset for $targetFramework."
            }

            # File paths are case-insensitive on the supported Windows file system
            # but case-sensitive on typical Linux CI file systems. Matching the OS
            # avoids duplicate references without conflating distinct Unix paths.
            $pathComparer = if ($IsWindows) { [StringComparer]::OrdinalIgnoreCase } else { [StringComparer]::Ordinal }
            $referenceSet = [Collections.Generic.HashSet[string]]::new($pathComparer)
            foreach ($resolvedReference in $resolvedReferences) {
                if ($resolvedReference.Path -ne $resolvedPackageAssemblies[0].Path) {
                    $null = $referenceSet.Add($resolvedReference.Path)
                }
            }
            $referencePaths = @($referenceSet | Sort-Object)

            $rawOutputPath = Join-Path $rawDirectory "OpenAI.$targetFramework.cs"
            # Tool restore above names the repository manifest explicitly, so tool
            # execution must run inside the repository. `dotnet tool run` has no
            # --tool-manifest option and searches from its working directory;
            # running this script from D:\openai, for example, cannot otherwise
            # discover openai-dotnet/.config/dotnet-tools.json.
            $genApiArguments = @(
                "tool", "run", "genapi", "--",
                "--assembly", $packageAssembly.AssemblyPath
            )
            foreach ($referencePath in $referencePaths) {
                $genApiArguments += @("--assembly-reference", $referencePath)
            }
            $genApiArguments += @("--output-path", $rawOutputPath)

            Write-Host "Running GenAPI for OpenAI $apiVersion ($targetFramework)..." -ForegroundColor Cyan
            $genApiResult = Invoke-DotNetCommand -Arguments $genApiArguments -WorkingDirectory $RepositoryRoot
            $genApiOutput = @($genApiResult.StandardOutput, $genApiResult.StandardError) | Where-Object { $_ } | Join-String -Separator ([Environment]::NewLine)
            if ($genApiOutput) {
                Write-Host $genApiOutput.Trim()
            }
            # This GenAPI version reports some unresolved references as ordinary
            # messages and may still exit with code zero. Treat the known messages
            # as failures so a partial listing cannot be promoted as authoritative.
            # Example: "Could not resolve reference 'System.ClientModel' ...".
            if ($genApiOutput -match 'Could not resolve reference|Could not find matching assembly|Could not find the provided path') {
                throw "GenAPI reported an unresolved reference for $targetFramework."
            }
            if (-not (Test-Path $rawOutputPath -PathType Leaf) -or (Get-Item $rawOutputPath).Length -eq 0) {
                throw "GenAPI did not produce a nonempty output file for $targetFramework."
            }

            $content = Get-Content $rawOutputPath -Raw
            if ($content -cnotmatch '(?m)^namespace OpenAI') {
                throw "GenAPI output contained no OpenAI namespace for $targetFramework."
            }
            $content = Format-ApiListing -Content $content -GeneratedHeader $releasedHeader
            Split-Artifact -Content $content -TargetFramework $targetFramework -ProjectName "OpenAI" -OutputDirectory $formattedDirectory -GeneratedHeader $releasedHeader

            # Validate each framework while output is still isolated in staging.
            # A net8.0 file must be named *.net8.0.cs, carry the released header,
            # and contain exactly one namespace because Split-Artifact promises
            # one namespace per file.
            $stagedFiles = @(Get-ChildItem (Join-Path $formattedDirectory $targetFramework) -Filter "*.cs" -File)
            if ($stagedFiles.Count -eq 0) {
                throw "No formatted API listings were generated for $targetFramework."
            }
            foreach ($stagedFile in $stagedFiles) {
                $stagedContent = Get-Content $stagedFile.FullName -Raw
                if (-not $stagedFile.Name.EndsWith(".$targetFramework.cs", [StringComparison]::Ordinal) -or
                    -not $stagedContent.StartsWith($releasedHeader, [StringComparison]::Ordinal) -or
                    [regex]::Matches($stagedContent, '(?m)^namespace OpenAI').Count -ne 1) {
                    throw "Formatted API listing validation failed: $($stagedFile.FullName)"
                }
            }
        }

        $expectedFrameworks = @($packageAssemblies.TargetFramework | Sort-Object)
        $stagedFrameworks = @(Get-ChildItem $formattedDirectory -Directory | ForEach-Object Name | Sort-Object)
        if (@(Compare-Object $expectedFrameworks $stagedFrameworks).Count -ne 0) {
            throw "Staged target frameworks do not match the package assets."
        }

        # Replace the live tree only after every framework succeeds. The sequence
        # is `released -> backup`, `formatted -> released`, then delete backup.
        # If the second move fails, the catch restores the original directory, so
        # consumers never observe a partly regenerated framework set.
        Write-Host "Promoting released API listings..." -ForegroundColor Cyan
        try {
            if (Test-Path $outputDirectory) {
                Move-Item $outputDirectory $backupDirectory
            }
            Move-Item $formattedDirectory $outputDirectory
            if (Test-Path $backupDirectory) {
                Remove-Item $backupDirectory -Recurse -Force
            }
        }
        catch {
            if (Test-Path $outputDirectory) {
                Remove-Item $outputDirectory -Recurse -Force
            }
            if (Test-Path $backupDirectory) {
                Move-Item $backupDirectory $outputDirectory
            }
            throw
        }

        Write-Host "Released API generation completed successfully." -ForegroundColor Green
    }
    finally {
        if (Test-Path $workRoot) {
            Remove-Item $workRoot -Recurse -Force
        }
    }
}

# ── Main Script ───────────────────────────────────────────────────────────────

$configuration = "Release"

# Resolve paths
$repoRootPath = Join-Path $PSScriptRoot ".." -Resolve

# Branch before initializing or cleaning the current-source directories. This is
# the ownership boundary that guarantees -Released cannot modify api/in-progress.
if ($Released) {
    Invoke-ReleasedApiExport -RepositoryRoot $repoRootPath
    return
}

$outputDirectory = Join-Path $repoRootPath "api" "in-progress"
$intermediateDirectory = Join-Path $repoRootPath "artifacts" "api"

# Projects to export. Each entry has a project file path and the library name
# used as the prefix for the generated API files.
$projects = @(
    @{
        Name = "OpenAI"
        Path = Join-Path $repoRootPath "OpenAI" "src" "OpenAI.csproj"
    }
)

# Get ClientTargetFrameworks from Directory.Build.props
$propsPath = Join-Path $repoRootPath "Directory.Build.props"
$clientTargetFrameworks = ""
if (Test-Path $propsPath) {
    $propsContent = Get-Content $propsPath -Raw
    if ($propsContent -match '<ClientTargetFrameworks>([^<]+)</ClientTargetFrameworks>') {
        $clientTargetFrameworks = $Matches[1]
    }
}

if (-not $clientTargetFrameworks) {
    Write-Error "Could not find ClientTargetFrameworks in Directory.Build.props"
    exit 1
}

$targetFrameworks = $clientTargetFrameworks -split ';' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
$generatedHeader = Get-GeneratedHeader

Write-Host ""
Write-Host "Target Frameworks: $clientTargetFrameworks" -ForegroundColor Green
Write-Host "Configuration: $configuration"
Write-Host ""

# Ensure output directories exist and are clean (only remove generated .cs files, not other files like README.md)
if (Test-Path $outputDirectory) {
    Write-Host "Cleaning existing output directory..." -ForegroundColor Cyan
    try {
        foreach ($project in $projects) {
            foreach ($targetFramework in $targetFrameworks) {
                $targetFrameworkDirectory = Join-Path $outputDirectory $targetFramework
                if (Test-Path $targetFrameworkDirectory) {
                    Get-ChildItem -Path $targetFrameworkDirectory -Filter "$($project.Name)*.$targetFramework.cs" -Force | Remove-Item -Force
                }
                else {
                    New-Item -ItemType Directory -Path $targetFrameworkDirectory -Force | Out-Null
                }
            }
        }
    }
    catch {
        Write-Warning "Failed to clean some items in output directory: $_"
    }
} else {
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
    Write-Host "Created output directory: $outputDirectory"
}

if (Test-Path $intermediateDirectory) {
    Remove-Item -Path $intermediateDirectory -Recurse -Force
}
New-Item -ItemType Directory -Path $intermediateDirectory -Force | Out-Null

Write-Host "Output Directory: $outputDirectory"
Write-Host "Intermediate Directory: $intermediateDirectory"
Write-Host ""

foreach ($project in $projects) {
    $projectName = $project.Name
    $projectPath = $project.Path

    Write-Host "================================================================" -ForegroundColor Cyan
    Write-Host "Running GenAPI for $projectName..." -ForegroundColor Cyan
    Write-Host "================================================================" -ForegroundColor Cyan
    Write-Host ""

    # Build the dotnet command arguments
    $buildArgs = @(
        "build"
        $projectPath
        "-t:ExportApi"
        "-c:$configuration"
        "-p:ExportingApi=true"
        "-m"
    )

    # Run a single build command - the MSBuild target handles all frameworks
    & dotnet @buildArgs
    if ($LASTEXITCODE -ne 0) {
        Write-Error "GenAPI failed for $projectName with exit code $LASTEXITCODE"
        exit $LASTEXITCODE
    }

    Write-Host ""
    Write-Host "Cleaning and splitting generated files for $projectName..." -ForegroundColor Cyan

    foreach ($targetFramework in $targetFrameworks) {
        $generatedFile = Join-Path $intermediateDirectory "$projectName.$targetFramework.cs"

        if (-not (Test-Path $generatedFile)) {
            throw "Expected generated API file was not found: $generatedFile"
        }

        Write-Host "  Processing $projectName.$targetFramework.cs..."

        $content = Get-Content $generatedFile -Raw
        $content = Format-ApiListing -Content $content -GeneratedHeader $generatedHeader
        Split-Artifact -Content $content -TargetFramework $targetFramework -ProjectName $projectName -OutputDirectory $outputDirectory -GeneratedHeader $generatedHeader
        Remove-Item -Path $generatedFile -Force
    }

    Write-Host ""
}

if (Test-Path $intermediateDirectory) {
    Remove-Item -Path $intermediateDirectory -Recurse -Force
}

Write-Host "API generation completed successfully." -ForegroundColor Green
Write-Host ""

# List generated files
Write-Host "Generated files:" -ForegroundColor Cyan
foreach ($project in $projects) {
    foreach ($targetFramework in $targetFrameworks) {
        $targetFrameworkDirectory = Join-Path $outputDirectory $targetFramework
        Get-ChildItem -Path $targetFrameworkDirectory -Filter "$($project.Name)*.$targetFramework.cs" | Sort-Object Name | ForEach-Object {
            Write-Host "  - $targetFramework/$($_.Name)"
        }
    }
}
Write-Host ""
