using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace OpenAI.Chat;

/// <summary>
/// Represents the audio output generated by the model as part of a chat completion response.
/// </summary>
[CodeGenModel("ChatCompletionResponseMessageAudio")]
public partial class ChatOutputAudio
{
    // CUSTOM: Renamed.
    [CodeGenMember("Data")]
    public BinaryData AudioBytes { get; }
}