using System;
using System.Diagnostics.CodeAnalysis;

namespace OpenAI.Chat;

// CUSTOM: Added Experimental attribute.
/// <summary>
/// Represents the audio output generated by the model as part of a chat completion response.
/// </summary>
[Experimental("OPENAI001")]
[CodeGenType("ChatCompletionResponseMessageAudio1")]
public partial class ChatOutputAudio
{
    // CUSTOM: Renamed.
    [CodeGenMember("Data")]
    public BinaryData AudioBytes { get; }
}