//------------------------------------------------------------------------------
// <auto-generated>
//     This file is auto-generated by scripts/Export-Api.ps1 and must not be
//     modified manually. To update it, make the necessary source-code changes
//     and re-run scripts/Export-Api.ps1 to regenerate it.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OpenAI.Containers {
    [Experimental("OPENAI001")]
    public class ContainerAllowlistNetworkPolicy : ContainerNetworkPolicy, IJsonModel<ContainerAllowlistNetworkPolicy>, IPersistableModel<ContainerAllowlistNetworkPolicy> {
        public ContainerAllowlistNetworkPolicy() : base(default);
        public ContainerAllowlistNetworkPolicy(IEnumerable<string> allowedDomains) : base(default);
        public IList<string> AllowedDomains { get; }
        public IList<ContainerNetworkPolicyDomainSecret> DomainSecrets { get; }
    }
    [Experimental("OPENAI001")]
    public class ContainerClient {
        protected ContainerClient();
        [Experimental("SCME0002")]
        public ContainerClient(ContainerClientSettings settings);
        public ContainerClient(ApiKeyCredential credential, OpenAIClientOptions options);
        public ContainerClient(ApiKeyCredential credential);
        public ContainerClient(AuthenticationPolicy authenticationPolicy, OpenAIClientOptions options);
        public ContainerClient(AuthenticationPolicy authenticationPolicy);
        protected internal ContainerClient(ClientPipeline pipeline, OpenAIClientOptions options);
        public ContainerClient(string apiKey);
        [Experimental("OPENAI001")]
        public Uri Endpoint { get; }
        public ClientPipeline Pipeline { get; }
        public virtual ClientResult<ContainerResource> CreateContainer(ContainerCreationOptions options, CancellationToken cancellationToken = default);
        public virtual ClientResult CreateContainer(BinaryContent content, RequestOptions options = null);
        public virtual Task<ClientResult<ContainerResource>> CreateContainerAsync(ContainerCreationOptions options, CancellationToken cancellationToken = default);
        public virtual Task<ClientResult> CreateContainerAsync(BinaryContent content, RequestOptions options = null);
        public virtual ClientResult DeleteContainer(string containerId, RequestOptions options);
        public virtual ClientResult<ContainerDeletionResult> DeleteContainer(string containerId, CancellationToken cancellationToken = default);
        public virtual Task<ClientResult> DeleteContainerAsync(string containerId, RequestOptions options);
        public virtual Task<ClientResult<ContainerDeletionResult>> DeleteContainerAsync(string containerId, CancellationToken cancellationToken = default);
        public virtual ClientResult DeleteContainerFile(string containerId, string fileId, RequestOptions options);
        public virtual ClientResult<ContainerFileDeletionResult> DeleteContainerFile(string containerId, string fileId, CancellationToken cancellationToken = default);
        public virtual Task<ClientResult> DeleteContainerFileAsync(string containerId, string fileId, RequestOptions options);
        public virtual Task<ClientResult<ContainerFileDeletionResult>> DeleteContainerFileAsync(string containerId, string fileId, CancellationToken cancellationToken = default);
        public virtual ClientResult DownloadContainerFile(string containerId, string fileId, RequestOptions options);
        public virtual ClientResult<BinaryData> DownloadContainerFile(string containerId, string fileId, CancellationToken cancellationToken = default);
        public virtual Task<ClientResult> DownloadContainerFileAsync(string containerId, string fileId, RequestOptions options);
        public virtual Task<ClientResult<BinaryData>> DownloadContainerFileAsync(string containerId, string fileId, CancellationToken cancellationToken = default);
        public virtual ClientResult GetContainer(string containerId, RequestOptions options);
        public virtual ClientResult<ContainerResource> GetContainer(string containerId, CancellationToken cancellationToken = default);
        public virtual Task<ClientResult> GetContainerAsync(string containerId, RequestOptions options);
        public virtual Task<ClientResult<ContainerResource>> GetContainerAsync(string containerId, CancellationToken cancellationToken = default);
        public virtual ClientResult<ContainerCollectionPage> GetContainerCollectionPage(ContainerCollectionOptions options = null, CancellationToken cancellationToken = default);
        public virtual ClientResult GetContainerCollectionPage(int? limit, string order, string after, string name, RequestOptions options);
        public virtual Task<ClientResult<ContainerCollectionPage>> GetContainerCollectionPageAsync(ContainerCollectionOptions options = null, CancellationToken cancellationToken = default);
        public virtual Task<ClientResult> GetContainerCollectionPageAsync(int? limit, string order, string after, string name, RequestOptions options);
        public virtual ClientResult GetContainerFile(string containerId, string fileId, RequestOptions options);
        public virtual ClientResult<ContainerFileResource> GetContainerFile(string containerId, string fileId, CancellationToken cancellationToken = default);
        public virtual Task<ClientResult> GetContainerFileAsync(string containerId, string fileId, RequestOptions options);
        public virtual Task<ClientResult<ContainerFileResource>> GetContainerFileAsync(string containerId, string fileId, CancellationToken cancellationToken = default);
        public virtual ClientResult<ContainerFileCollectionPage> GetContainerFileCollectionPage(ContainerFileCollectionOptions options, CancellationToken cancellationToken = default);
        public virtual ClientResult GetContainerFileCollectionPage(string containerId, int? limit, string order, string after, RequestOptions options);
        public virtual Task<ClientResult<ContainerFileCollectionPage>> GetContainerFileCollectionPageAsync(ContainerFileCollectionOptions options, CancellationToken cancellationToken = default);
        public virtual Task<ClientResult> GetContainerFileCollectionPageAsync(string containerId, int? limit, string order, string after, RequestOptions options);
        public virtual CollectionResult<ContainerFileResource> GetContainerFiles(ContainerFileCollectionOptions options, CancellationToken cancellationToken = default);
        public virtual AsyncCollectionResult<ContainerFileResource> GetContainerFilesAsync(ContainerFileCollectionOptions options, CancellationToken cancellationToken = default);
        public virtual CollectionResult<ContainerResource> GetContainers(ContainerCollectionOptions options = null, CancellationToken cancellationToken = default);
        public virtual AsyncCollectionResult<ContainerResource> GetContainersAsync(ContainerCollectionOptions options = null, CancellationToken cancellationToken = default);
        public virtual ClientResult UploadContainerFile(string containerId, BinaryContent content, string contentType, RequestOptions options = null);
        public virtual Task<ClientResult> UploadContainerFileAsync(string containerId, BinaryContent content, string contentType, RequestOptions options = null);
    }
    [Experimental("SCME0002")]
    public sealed class ContainerClientSettings : ClientSettings {
        public OpenAIClientOptions Options { get; set; }
        protected override void BindCore(Microsoft.Extensions.Configuration.IConfigurationSection section);
    }
    [Experimental("OPENAI001")]
    public class ContainerCollectionOptions : IJsonModel<ContainerCollectionOptions>, IPersistableModel<ContainerCollectionOptions> {
        public string AfterId { get; set; }
        public string Name { get; set; }
        public ContainerCollectionOrder? Order { get; set; }
        public int? PageSizeLimit { get; set; }
    }
    [Experimental("OPENAI001")]
    public readonly partial struct ContainerCollectionOrder : IEquatable<ContainerCollectionOrder> {
        public ContainerCollectionOrder(string value);
        public static ContainerCollectionOrder Ascending { get; }
        public static ContainerCollectionOrder Descending { get; }
        public readonly bool Equals(ContainerCollectionOrder other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(ContainerCollectionOrder left, ContainerCollectionOrder right);
        public static implicit operator ContainerCollectionOrder(string value);
        public static implicit operator ContainerCollectionOrder?(string value);
        public static bool operator !=(ContainerCollectionOrder left, ContainerCollectionOrder right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public class ContainerCollectionPage : IJsonModel<ContainerCollectionPage>, IPersistableModel<ContainerCollectionPage> {
        public IList<ContainerResource> Data { get; }
        public string FirstId { get; set; }
        public bool HasMore { get; set; }
        public string LastId { get; set; }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string Object { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public static explicit operator ContainerCollectionPage(ClientResult result);
    }
    [Experimental("OPENAI001")]
    public class ContainerCreationOptions : IJsonModel<ContainerCreationOptions>, IPersistableModel<ContainerCreationOptions> {
        public ContainerCreationOptions();
        public ContainerCreationOptions(string name);
        public ContainerExpirationPolicy ExpirationPolicy { get; set; }
        public IList<string> FileIds { get; }
        public ContainerMemoryLimit? MemoryLimit { get; set; }
        public string Name { get; set; }
        public ContainerNetworkPolicy NetworkPolicy { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public static implicit operator BinaryContent(ContainerCreationOptions containerCreationOptions);
    }
    [Experimental("OPENAI001")]
    public class ContainerDeletionResult : IJsonModel<ContainerDeletionResult>, IPersistableModel<ContainerDeletionResult> {
        public string ContainerId { get; set; }
        public bool Deleted { get; set; }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string Object { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public static explicit operator ContainerDeletionResult(ClientResult result);
    }
    [Experimental("OPENAI001")]
    public class ContainerDisabledNetworkPolicy : ContainerNetworkPolicy, IJsonModel<ContainerDisabledNetworkPolicy>, IPersistableModel<ContainerDisabledNetworkPolicy> {
        public ContainerDisabledNetworkPolicy() : base(default);
    }
    [Experimental("OPENAI001")]
    public class ContainerExpirationPolicy : IJsonModel<ContainerExpirationPolicy>, IPersistableModel<ContainerExpirationPolicy> {
        public ContainerExpirationPolicyAnchor? Anchor { get; set; }
        public TimeSpan? Duration { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
    }
    [Experimental("OPENAI001")]
    public readonly partial struct ContainerExpirationPolicyAnchor : IEquatable<ContainerExpirationPolicyAnchor> {
        public ContainerExpirationPolicyAnchor(string value);
        public static ContainerExpirationPolicyAnchor LastActiveAt { get; }
        public readonly bool Equals(ContainerExpirationPolicyAnchor other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(ContainerExpirationPolicyAnchor left, ContainerExpirationPolicyAnchor right);
        public static implicit operator ContainerExpirationPolicyAnchor(string value);
        public static implicit operator ContainerExpirationPolicyAnchor?(string value);
        public static bool operator !=(ContainerExpirationPolicyAnchor left, ContainerExpirationPolicyAnchor right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public class ContainerFileCollectionOptions : IJsonModel<ContainerFileCollectionOptions>, IPersistableModel<ContainerFileCollectionOptions> {
        public ContainerFileCollectionOptions();
        public ContainerFileCollectionOptions(string containerId);
        public string AfterId { get; set; }
        public string ContainerId { get; set; }
        public ContainerFileCollectionOrder? Order { get; set; }
        public int? PageSizeLimit { get; set; }
    }
    [Experimental("OPENAI001")]
    public readonly partial struct ContainerFileCollectionOrder : IEquatable<ContainerFileCollectionOrder> {
        public ContainerFileCollectionOrder(string value);
        public static ContainerFileCollectionOrder Ascending { get; }
        public static ContainerFileCollectionOrder Descending { get; }
        public readonly bool Equals(ContainerFileCollectionOrder other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(ContainerFileCollectionOrder left, ContainerFileCollectionOrder right);
        public static implicit operator ContainerFileCollectionOrder(string value);
        public static implicit operator ContainerFileCollectionOrder?(string value);
        public static bool operator !=(ContainerFileCollectionOrder left, ContainerFileCollectionOrder right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public class ContainerFileCollectionPage : IJsonModel<ContainerFileCollectionPage>, IPersistableModel<ContainerFileCollectionPage> {
        public IList<ContainerFileResource> Data { get; }
        public string FirstId { get; set; }
        public bool HasMore { get; set; }
        public string LastId { get; set; }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string Object { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public static explicit operator ContainerFileCollectionPage(ClientResult result);
    }
    [Experimental("OPENAI001")]
    public class ContainerFileDeletionResult : IJsonModel<ContainerFileDeletionResult>, IPersistableModel<ContainerFileDeletionResult> {
        public string ContainerFileId { get; set; }
        public bool Deleted { get; set; }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string Object { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public static explicit operator ContainerFileDeletionResult(ClientResult result);
    }
    [Experimental("OPENAI001")]
    public class ContainerFileResource : IJsonModel<ContainerFileResource>, IPersistableModel<ContainerFileResource> {
        public string ContainerId { get; set; }
        public DateTimeOffset CreatedOn { get; set; }
        public string Id { get; set; }
        public string Object { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public string Path { get; set; }
        public long? SizeInBytes { get; set; }
        public string Source { get; set; }
        public static explicit operator ContainerFileResource(ClientResult result);
    }
    [Experimental("OPENAI001")]
    public readonly partial struct ContainerMemoryLimit : IEquatable<ContainerMemoryLimit> {
        public ContainerMemoryLimit(string value);
        public static ContainerMemoryLimit Max16GB { get; }
        public static ContainerMemoryLimit Max1GB { get; }
        public static ContainerMemoryLimit Max4GB { get; }
        public static ContainerMemoryLimit Max64GB { get; }
        public readonly bool Equals(ContainerMemoryLimit other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(ContainerMemoryLimit left, ContainerMemoryLimit right);
        public static implicit operator ContainerMemoryLimit(string value);
        public static implicit operator ContainerMemoryLimit?(string value);
        public static bool operator !=(ContainerMemoryLimit left, ContainerMemoryLimit right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public class ContainerNetworkPolicy : IJsonModel<ContainerNetworkPolicy>, IPersistableModel<ContainerNetworkPolicy> {
        protected internal ContainerNetworkPolicy(ContainerNetworkPolicyKind kind);
        public ContainerNetworkPolicyKind Kind { get; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
    }
    [Experimental("OPENAI001")]
    public class ContainerNetworkPolicyDomainSecret : IJsonModel<ContainerNetworkPolicyDomainSecret>, IPersistableModel<ContainerNetworkPolicyDomainSecret> {
        public ContainerNetworkPolicyDomainSecret();
        public ContainerNetworkPolicyDomainSecret(string domain, string name, string value);
        public string Domain { get; set; }
        public string Name { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public string Value { get; set; }
    }
    [Experimental("OPENAI001")]
    public readonly partial struct ContainerNetworkPolicyKind : IEquatable<ContainerNetworkPolicyKind> {
        public ContainerNetworkPolicyKind(string value);
        public static ContainerNetworkPolicyKind Allowlist { get; }
        public static ContainerNetworkPolicyKind Disabled { get; }
        public readonly bool Equals(ContainerNetworkPolicyKind other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(ContainerNetworkPolicyKind left, ContainerNetworkPolicyKind right);
        public static implicit operator ContainerNetworkPolicyKind(string value);
        public static implicit operator ContainerNetworkPolicyKind?(string value);
        public static bool operator !=(ContainerNetworkPolicyKind left, ContainerNetworkPolicyKind right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public class ContainerResource : IJsonModel<ContainerResource>, IPersistableModel<ContainerResource> {
        public DateTimeOffset CreatedOn { get; set; }
        public ContainerExpirationPolicy ExpirationPolicy { get; set; }
        public string Id { get; set; }
        public DateTimeOffset? LastActiveOn { get; set; }
        public ContainerMemoryLimit? MemoryLimit { get; set; }
        public string Name { get; set; }
        public ContainerNetworkPolicy NetworkPolicy { get; set; }
        public string Object { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public string Status { get; set; }
        public static explicit operator ContainerResource(ClientResult result);
    }
}