//------------------------------------------------------------------------------
// <auto-generated>
//     This file is auto-generated by scripts/Export-Api.ps1 and must not be
//     modified manually. To update it, make the necessary source-code changes
//     and re-run scripts/Export-Api.ps1 to regenerate it.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OpenAI.Conversations {
    [Experimental("OPENAI001")]
    public class ConversationClient {
        protected ConversationClient();
        [Experimental("SCME0002")]
        public ConversationClient(ConversationClientSettings settings);
        public ConversationClient(ApiKeyCredential credential, OpenAIClientOptions options);
        public ConversationClient(ApiKeyCredential credential);
        public ConversationClient(AuthenticationPolicy authenticationPolicy, OpenAIClientOptions options);
        public ConversationClient(AuthenticationPolicy authenticationPolicy);
        protected internal ConversationClient(ClientPipeline pipeline, OpenAIClientOptions options);
        public ConversationClient(string apiKey);
        [Experimental("OPENAI001")]
        public Uri Endpoint { get; }
        public ClientPipeline Pipeline { get; }
        public virtual ClientResult<ConversationResource> CreateConversation(ConversationCreationOptions options, CancellationToken cancellationToken = default);
        public virtual ClientResult CreateConversation(BinaryContent content, RequestOptions options = null);
        public virtual Task<ClientResult<ConversationResource>> CreateConversationAsync(ConversationCreationOptions options, CancellationToken cancellationToken = default);
        public virtual Task<ClientResult> CreateConversationAsync(BinaryContent content, RequestOptions options = null);
        public virtual ClientResult CreateConversationItems(string conversationId, BinaryContent content, IEnumerable<IncludedConversationItemProperty> include = null, RequestOptions options = null);
        public virtual Task<ClientResult> CreateConversationItemsAsync(string conversationId, BinaryContent content, IEnumerable<IncludedConversationItemProperty> include = null, RequestOptions options = null);
        public virtual ClientResult DeleteConversation(string conversationId, RequestOptions options);
        public virtual ClientResult<ConversationDeletionResult> DeleteConversation(string conversationId, CancellationToken cancellationToken = default);
        public virtual Task<ClientResult> DeleteConversationAsync(string conversationId, RequestOptions options);
        public virtual Task<ClientResult<ConversationDeletionResult>> DeleteConversationAsync(string conversationId, CancellationToken cancellationToken = default);
        public virtual ClientResult DeleteConversationItem(string conversationId, string itemId, RequestOptions options = null);
        public virtual Task<ClientResult> DeleteConversationItemAsync(string conversationId, string itemId, RequestOptions options = null);
        public virtual ClientResult GetConversation(string conversationId, RequestOptions options);
        public virtual ClientResult<ConversationResource> GetConversation(string conversationId, CancellationToken cancellationToken = default);
        public virtual Task<ClientResult> GetConversationAsync(string conversationId, RequestOptions options);
        public virtual Task<ClientResult<ConversationResource>> GetConversationAsync(string conversationId, CancellationToken cancellationToken = default);
        public virtual ClientResult GetConversationItem(string conversationId, string itemId, IEnumerable<IncludedConversationItemProperty> include = null, RequestOptions options = null);
        public virtual Task<ClientResult> GetConversationItemAsync(string conversationId, string itemId, IEnumerable<IncludedConversationItemProperty> include = null, RequestOptions options = null);
        public virtual CollectionResult GetConversationItems(string conversationId, int? limit = null, string order = null, string after = null, IEnumerable<IncludedConversationItemProperty> include = null, RequestOptions options = null);
        public virtual AsyncCollectionResult GetConversationItemsAsync(string conversationId, int? limit = null, string order = null, string after = null, IEnumerable<IncludedConversationItemProperty> include = null, RequestOptions options = null);
        public virtual ClientResult<ConversationResource> UpdateConversation(string conversationId, ConversationUpdateOptions options, CancellationToken cancellationToken = default);
        public virtual ClientResult UpdateConversation(string conversationId, BinaryContent content, RequestOptions options = null);
        public virtual Task<ClientResult<ConversationResource>> UpdateConversationAsync(string conversationId, ConversationUpdateOptions options, CancellationToken cancellationToken = default);
        public virtual Task<ClientResult> UpdateConversationAsync(string conversationId, BinaryContent content, RequestOptions options = null);
    }
    [Experimental("SCME0002")]
    public sealed class ConversationClientSettings : ClientSettings {
        public OpenAIClientOptions Options { get; set; }
        protected override void BindCore(Microsoft.Extensions.Configuration.IConfigurationSection section);
    }
    [Experimental("OPENAI001")]
    public class ConversationCreationOptions : IJsonModel<ConversationCreationOptions>, IPersistableModel<ConversationCreationOptions> {
        public IList<Responses.ResponseItem> Items { get; }
        public IDictionary<string, string> Metadata { get; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public static implicit operator BinaryContent(ConversationCreationOptions conversationCreationOptions);
    }
    [Experimental("OPENAI001")]
    public class ConversationDeletionResult : IJsonModel<ConversationDeletionResult>, IPersistableModel<ConversationDeletionResult> {
        public string ConversationId { get; set; }
        public bool Deleted { get; set; }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string Object { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public static explicit operator ConversationDeletionResult(ClientResult result);
    }
    [Experimental("OPENAI001")]
    public class ConversationResource : IJsonModel<ConversationResource>, IPersistableModel<ConversationResource> {
        public DateTimeOffset CreatedOn { get; set; }
        public string Id { get; set; }
        public IDictionary<string, string> Metadata { get; }
        [EditorBrowsable(EditorBrowsableState.Never)]
        public string Object { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public static explicit operator ConversationResource(ClientResult result);
    }
    [Experimental("OPENAI001")]
    public class ConversationUpdateOptions : IJsonModel<ConversationUpdateOptions>, IPersistableModel<ConversationUpdateOptions> {
        public ConversationUpdateOptions();
        public ConversationUpdateOptions(IDictionary<string, string> metadata);
        public IDictionary<string, string> Metadata { get; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public static implicit operator BinaryContent(ConversationUpdateOptions conversationUpdateOptions);
    }
    [Experimental("OPENAI001")]
    public readonly partial struct IncludedConversationItemProperty : IEquatable<IncludedConversationItemProperty> {
        public IncludedConversationItemProperty(string value);
        public static IncludedConversationItemProperty CodeInterpreterCallOutputs { get; }
        public static IncludedConversationItemProperty ComputerCallOutputImageUri { get; }
        public static IncludedConversationItemProperty FileSearchCallResults { get; }
        public static IncludedConversationItemProperty MessageInputImageUri { get; }
        public static IncludedConversationItemProperty MessageOutputTextLogProbabilities { get; }
        public static IncludedConversationItemProperty ReasoningEncryptedContent { get; }
        public static IncludedConversationItemProperty WebSearchCallActionSources { get; }
        public static IncludedConversationItemProperty WebSearchCallResults { get; }
        public readonly bool Equals(IncludedConversationItemProperty other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(IncludedConversationItemProperty left, IncludedConversationItemProperty right);
        public static implicit operator IncludedConversationItemProperty(string value);
        public static implicit operator IncludedConversationItemProperty?(string value);
        public static bool operator !=(IncludedConversationItemProperty left, IncludedConversationItemProperty right);
        public override readonly string ToString();
    }
}