//------------------------------------------------------------------------------
// <auto-generated>
//     This file is auto-generated by scripts/Export-Api.ps1 and must not be
//     modified manually. To update it, make the necessary source-code changes
//     and re-run scripts/Export-Api.ps1 to regenerate it.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OpenAI.Agents {
    [Experimental("OPENAI001")]
    public class Agent : IJsonModel<Agent>, IPersistableModel<Agent> {
        public int CreatedAt { get; set; }
        public string Id { get; set; }
        public string Instructions { get; set; }
        public IDictionary<string, string> Metadata { get; }
        public string Model { get; set; }
        public MultiAgentConfigResource MultiAgent { get; set; }
        public string Name { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public ReasoningResource Reasoning { get; set; }
        public ServiceTierResource ServiceTier { get; set; }
        public TextResource Text { get; set; }
        public IList<PersistedAgentToolResource> Tools { get; }
        public int UpdatedAt { get; set; }
        public static explicit operator Agent(ClientResult result);
    }
    [Experimental("OPENAI001")]
    public class AgentClient {
        protected AgentClient();
        public ClientPipeline Pipeline { get; }
        public virtual ClientResult<Agent> CreateAgent(AgentCreationOptions agent, CancellationToken cancellationToken = default);
        public virtual ClientResult CreateAgent(BinaryContent content, RequestOptions options = null);
        public virtual Task<ClientResult<Agent>> CreateAgentAsync(AgentCreationOptions agent, CancellationToken cancellationToken = default);
        public virtual Task<ClientResult> CreateAgentAsync(BinaryContent content, RequestOptions options = null);
        public virtual ClientResult RetrieveAgent(string agentId, RequestOptions options);
        public virtual ClientResult<Agent> RetrieveAgent(string agentId, CancellationToken cancellationToken = default);
        public virtual Task<ClientResult> RetrieveAgentAsync(string agentId, RequestOptions options);
        public virtual Task<ClientResult<Agent>> RetrieveAgentAsync(string agentId, CancellationToken cancellationToken = default);
        public virtual ClientResult<Agent> UpdateAgent(string agentId, AgentModificationOptions agent, CancellationToken cancellationToken = default);
        public virtual ClientResult UpdateAgent(string agentId, BinaryContent content, RequestOptions options = null);
        public virtual Task<ClientResult<Agent>> UpdateAgentAsync(string agentId, AgentModificationOptions agent, CancellationToken cancellationToken = default);
        public virtual Task<ClientResult> UpdateAgentAsync(string agentId, BinaryContent content, RequestOptions options = null);
    }
    [Experimental("OPENAI001")]
    public class AgentCreationOptions : IJsonModel<AgentCreationOptions>, IPersistableModel<AgentCreationOptions> {
        public AgentCreationOptions();
        public AgentCreationOptions(string model);
        public string Instructions { get; set; }
        public IDictionary<string, string> Metadata { get; set; }
        public string Model { get; set; }
        public MultiAgentConfigCurrentParam MultiAgent { get; set; }
        public string Name { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public ReasoningParam Reasoning { get; set; }
        public ServiceTierParam? ServiceTier { get; set; }
        public TextParam Text { get; set; }
        public IList<PersistedAgentToolConfigParam> Tools { get; set; }
        public static implicit operator BinaryContent(AgentCreationOptions agentCreationOptions);
    }
    [Experimental("OPENAI001")]
    public class AgentModificationOptions : IJsonModel<AgentModificationOptions>, IPersistableModel<AgentModificationOptions> {
        public string Instructions { get; set; }
        public IDictionary<string, string> Metadata { get; set; }
        public string Model { get; set; }
        public MultiAgentConfigCurrentParam MultiAgent { get; set; }
        public string Name { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public ReasoningParam Reasoning { get; set; }
        public ServiceTierParam? ServiceTier { get; set; }
        public TextParam Text { get; set; }
        public IList<PersistedAgentToolConfigParam> Tools { get; set; }
        public static implicit operator BinaryContent(AgentModificationOptions agentModificationOptions);
    }
    [Experimental("OPENAI001")]
    public readonly partial struct McpConnectionOriginParam : IEquatable<McpConnectionOriginParam> {
        public McpConnectionOriginParam(string value);
        public static McpConnectionOriginParam Environment { get; }
        public static McpConnectionOriginParam Service { get; }
        public readonly bool Equals(McpConnectionOriginParam other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(McpConnectionOriginParam left, McpConnectionOriginParam right);
        public static implicit operator McpConnectionOriginParam(string value);
        public static implicit operator McpConnectionOriginParam?(string value);
        public static bool operator !=(McpConnectionOriginParam left, McpConnectionOriginParam right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public readonly partial struct McpConnectionOriginResource : IEquatable<McpConnectionOriginResource> {
        public McpConnectionOriginResource(string value);
        public static McpConnectionOriginResource Environment { get; }
        public static McpConnectionOriginResource Service { get; }
        public readonly bool Equals(McpConnectionOriginResource other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(McpConnectionOriginResource left, McpConnectionOriginResource right);
        public static implicit operator McpConnectionOriginResource(string value);
        public static implicit operator McpConnectionOriginResource?(string value);
        public static bool operator !=(McpConnectionOriginResource left, McpConnectionOriginResource right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public class MultiAgentConfigCurrentParam : IJsonModel<MultiAgentConfigCurrentParam>, IPersistableModel<MultiAgentConfigCurrentParam> {
        public MultiAgentConfigCurrentParam();
        public MultiAgentConfigCurrentParam(bool enabled);
        public bool Enabled { get; set; }
        public int? MaxConcurrentSubagents { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
    }
    [Experimental("OPENAI001")]
    public class MultiAgentConfigResource : IJsonModel<MultiAgentConfigResource>, IPersistableModel<MultiAgentConfigResource> {
        public bool Enabled { get; set; }
        public int? MaxConcurrentSubagents { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
    }
    [Experimental("OPENAI001")]
    public class PersistedAgentToolConfigParam : IJsonModel<PersistedAgentToolConfigParam>, IPersistableModel<PersistedAgentToolConfigParam> {
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
    }
    [Experimental("OPENAI001")]
    public class PersistedAgentToolConfigParamFunction : PersistedAgentToolConfigParam, IJsonModel<PersistedAgentToolConfigParamFunction>, IPersistableModel<PersistedAgentToolConfigParamFunction> {
        public PersistedAgentToolConfigParamFunction();
        public PersistedAgentToolConfigParamFunction(string name, string description, BinaryData parameters);
        public bool? DeferLoading { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public BinaryData Parameters { get; set; }
    }
    [Experimental("OPENAI001")]
    public class PersistedAgentToolConfigParamMcp : PersistedAgentToolConfigParam, IJsonModel<PersistedAgentToolConfigParamMcp>, IPersistableModel<PersistedAgentToolConfigParamMcp> {
        public PersistedAgentToolConfigParamMcp();
        public PersistedAgentToolConfigParamMcp(string serverLabel, PersistedMcpTransportConfigParam transport);
        public IList<string> AllowedTools { get; set; }
        public McpConnectionOriginParam? ConnectionOrigin { get; set; }
        public string CredentialId { get; set; }
        public BinaryData RequestMetadata { get; set; }
        public bool? Required { get; set; }
        public string ServerLabel { get; set; }
        public PersistedMcpTransportConfigParam Transport { get; set; }
    }
    [Experimental("OPENAI001")]
    public class PersistedAgentToolConfigParamProgrammaticToolCalling : PersistedAgentToolConfigParam, IJsonModel<PersistedAgentToolConfigParamProgrammaticToolCalling>, IPersistableModel<PersistedAgentToolConfigParamProgrammaticToolCalling> {
        public PersistedAgentToolConfigParamProgrammaticToolCalling();
        public bool? Enabled { get; set; }
    }
    [Experimental("OPENAI001")]
    public class PersistedAgentToolConfigParamToolSearch : PersistedAgentToolConfigParam, IJsonModel<PersistedAgentToolConfigParamToolSearch>, IPersistableModel<PersistedAgentToolConfigParamToolSearch> {
        public PersistedAgentToolConfigParamToolSearch();
    }
    [Experimental("OPENAI001")]
    public class PersistedAgentToolConfigParamWebSearch : PersistedAgentToolConfigParam, IJsonModel<PersistedAgentToolConfigParamWebSearch>, IPersistableModel<PersistedAgentToolConfigParamWebSearch> {
        public PersistedAgentToolConfigParamWebSearch();
        public IList<string> AllowedDomains { get; set; }
        public WebSearchContextSizeParam? ContextSize { get; set; }
        public WebSearchLocationParam Location { get; set; }
        public WebSearchModeParam? Mode { get; set; }
    }
    [Experimental("OPENAI001")]
    public class PersistedAgentToolResource : IJsonModel<PersistedAgentToolResource>, IPersistableModel<PersistedAgentToolResource> {
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
    }
    [Experimental("OPENAI001")]
    public class PersistedAgentToolResourceFunction : PersistedAgentToolResource, IJsonModel<PersistedAgentToolResourceFunction>, IPersistableModel<PersistedAgentToolResourceFunction> {
        public PersistedAgentToolResourceFunction();
        public bool DeferLoading { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public BinaryData Parameters { get; set; }
    }
    [Experimental("OPENAI001")]
    public class PersistedAgentToolResourceMcp : PersistedAgentToolResource, IJsonModel<PersistedAgentToolResourceMcp>, IPersistableModel<PersistedAgentToolResourceMcp> {
        public PersistedAgentToolResourceMcp();
        public IList<string> AllowedTools { get; }
        public McpConnectionOriginResource ConnectionOrigin { get; set; }
        public string CredentialId { get; set; }
        public BinaryData RequestMetadata { get; set; }
        public bool Required { get; set; }
        public string ServerLabel { get; set; }
        public PersistedMcpTransportResource Transport { get; set; }
    }
    [Experimental("OPENAI001")]
    public class PersistedAgentToolResourceProgrammaticToolCalling : PersistedAgentToolResource, IJsonModel<PersistedAgentToolResourceProgrammaticToolCalling>, IPersistableModel<PersistedAgentToolResourceProgrammaticToolCalling> {
        public PersistedAgentToolResourceProgrammaticToolCalling();
        public bool Enabled { get; set; }
    }
    [Experimental("OPENAI001")]
    public class PersistedAgentToolResourceToolSearch : PersistedAgentToolResource, IJsonModel<PersistedAgentToolResourceToolSearch>, IPersistableModel<PersistedAgentToolResourceToolSearch> {
        public PersistedAgentToolResourceToolSearch();
    }
    [Experimental("OPENAI001")]
    public class PersistedAgentToolResourceWebSearch : PersistedAgentToolResource, IJsonModel<PersistedAgentToolResourceWebSearch>, IPersistableModel<PersistedAgentToolResourceWebSearch> {
        public PersistedAgentToolResourceWebSearch();
        public IList<string> AllowedDomains { get; }
        public WebSearchContextSizeResource ContextSize { get; set; }
        public WebSearchLocationResource Location { get; set; }
        public WebSearchModeResource Mode { get; set; }
    }
    [Experimental("OPENAI001")]
    public readonly partial struct PersistedAgentToolType : IEquatable<PersistedAgentToolType> {
        public PersistedAgentToolType(string value);
        public static PersistedAgentToolType Function { get; }
        public static PersistedAgentToolType Mcp { get; }
        public static PersistedAgentToolType ProgrammaticToolCalling { get; }
        public static PersistedAgentToolType ToolSearch { get; }
        public static PersistedAgentToolType WebSearch { get; }
        public readonly bool Equals(PersistedAgentToolType other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(PersistedAgentToolType left, PersistedAgentToolType right);
        public static implicit operator PersistedAgentToolType(string value);
        public static implicit operator PersistedAgentToolType?(string value);
        public static bool operator !=(PersistedAgentToolType left, PersistedAgentToolType right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public class PersistedMcpTransportConfigParam : IJsonModel<PersistedMcpTransportConfigParam>, IPersistableModel<PersistedMcpTransportConfigParam> {
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
    }
    [Experimental("OPENAI001")]
    public class PersistedMcpTransportConfigParamHttp : PersistedMcpTransportConfigParam, IJsonModel<PersistedMcpTransportConfigParamHttp>, IPersistableModel<PersistedMcpTransportConfigParamHttp> {
        public PersistedMcpTransportConfigParamHttp();
        public PersistedMcpTransportConfigParamHttp(string serverUrl);
        public IDictionary<string, string> Headers { get; set; }
        public string ServerUrl { get; set; }
    }
    [Experimental("OPENAI001")]
    public class PersistedMcpTransportConfigParamStdio : PersistedMcpTransportConfigParam, IJsonModel<PersistedMcpTransportConfigParamStdio>, IPersistableModel<PersistedMcpTransportConfigParamStdio> {
        public PersistedMcpTransportConfigParamStdio();
        public PersistedMcpTransportConfigParamStdio(string command, string cwd);
        public IList<string> Args { get; set; }
        public string Command { get; set; }
        public string Cwd { get; set; }
        public IList<string> EnvVars { get; set; }
    }
    [Experimental("OPENAI001")]
    public class PersistedMcpTransportResource : IJsonModel<PersistedMcpTransportResource>, IPersistableModel<PersistedMcpTransportResource> {
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
    }
    [Experimental("OPENAI001")]
    public class PersistedMcpTransportResourceHttp : PersistedMcpTransportResource, IJsonModel<PersistedMcpTransportResourceHttp>, IPersistableModel<PersistedMcpTransportResourceHttp> {
        public PersistedMcpTransportResourceHttp();
        public IDictionary<string, string> Headers { get; }
        public string ServerUrl { get; set; }
    }
    [Experimental("OPENAI001")]
    public class PersistedMcpTransportResourceStdio : PersistedMcpTransportResource, IJsonModel<PersistedMcpTransportResourceStdio>, IPersistableModel<PersistedMcpTransportResourceStdio> {
        public PersistedMcpTransportResourceStdio();
        public IList<string> Args { get; }
        public string Command { get; set; }
        public string Cwd { get; set; }
        public IList<string> EnvVars { get; }
    }
    [Experimental("OPENAI001")]
    public readonly partial struct PersistedMcpTransportType : IEquatable<PersistedMcpTransportType> {
        public PersistedMcpTransportType(string value);
        public static PersistedMcpTransportType Http { get; }
        public static PersistedMcpTransportType Stdio { get; }
        public readonly bool Equals(PersistedMcpTransportType other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(PersistedMcpTransportType left, PersistedMcpTransportType right);
        public static implicit operator PersistedMcpTransportType(string value);
        public static implicit operator PersistedMcpTransportType?(string value);
        public static bool operator !=(PersistedMcpTransportType left, PersistedMcpTransportType right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public readonly partial struct ReasoningEffortParam : IEquatable<ReasoningEffortParam> {
        public ReasoningEffortParam(string value);
        public static ReasoningEffortParam High { get; }
        public static ReasoningEffortParam Low { get; }
        public static ReasoningEffortParam Max { get; }
        public static ReasoningEffortParam Medium { get; }
        public static ReasoningEffortParam Minimal { get; }
        public static ReasoningEffortParam None { get; }
        public static ReasoningEffortParam Xhigh { get; }
        public readonly bool Equals(ReasoningEffortParam other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(ReasoningEffortParam left, ReasoningEffortParam right);
        public static implicit operator ReasoningEffortParam(string value);
        public static implicit operator ReasoningEffortParam?(string value);
        public static bool operator !=(ReasoningEffortParam left, ReasoningEffortParam right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public readonly partial struct ReasoningEffortResource : IEquatable<ReasoningEffortResource> {
        public ReasoningEffortResource(string value);
        public static ReasoningEffortResource High { get; }
        public static ReasoningEffortResource Low { get; }
        public static ReasoningEffortResource Max { get; }
        public static ReasoningEffortResource Medium { get; }
        public static ReasoningEffortResource Minimal { get; }
        public static ReasoningEffortResource None { get; }
        public static ReasoningEffortResource Xhigh { get; }
        public readonly bool Equals(ReasoningEffortResource other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(ReasoningEffortResource left, ReasoningEffortResource right);
        public static implicit operator ReasoningEffortResource(string value);
        public static implicit operator ReasoningEffortResource?(string value);
        public static bool operator !=(ReasoningEffortResource left, ReasoningEffortResource right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public class ReasoningParam : IJsonModel<ReasoningParam>, IPersistableModel<ReasoningParam> {
        public ReasoningEffortParam? Effort { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public ReasoningSummaryParam? Summary { get; set; }
    }
    [Experimental("OPENAI001")]
    public class ReasoningResource : IJsonModel<ReasoningResource>, IPersistableModel<ReasoningResource> {
        public ReasoningEffortResource? Effort { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public ReasoningSummaryResource? Summary { get; set; }
    }
    [Experimental("OPENAI001")]
    public readonly partial struct ReasoningSummaryParam : IEquatable<ReasoningSummaryParam> {
        public ReasoningSummaryParam(string value);
        public static ReasoningSummaryParam Auto { get; }
        public static ReasoningSummaryParam Concise { get; }
        public static ReasoningSummaryParam Detailed { get; }
        public readonly bool Equals(ReasoningSummaryParam other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(ReasoningSummaryParam left, ReasoningSummaryParam right);
        public static implicit operator ReasoningSummaryParam(string value);
        public static implicit operator ReasoningSummaryParam?(string value);
        public static bool operator !=(ReasoningSummaryParam left, ReasoningSummaryParam right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public readonly partial struct ReasoningSummaryResource : IEquatable<ReasoningSummaryResource> {
        public ReasoningSummaryResource(string value);
        public static ReasoningSummaryResource Auto { get; }
        public static ReasoningSummaryResource Concise { get; }
        public static ReasoningSummaryResource Detailed { get; }
        public readonly bool Equals(ReasoningSummaryResource other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(ReasoningSummaryResource left, ReasoningSummaryResource right);
        public static implicit operator ReasoningSummaryResource(string value);
        public static implicit operator ReasoningSummaryResource?(string value);
        public static bool operator !=(ReasoningSummaryResource left, ReasoningSummaryResource right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public readonly partial struct ServiceTierParam : IEquatable<ServiceTierParam> {
        public ServiceTierParam(string value);
        public static ServiceTierParam Auto { get; }
        public static ServiceTierParam Default { get; }
        public static ServiceTierParam Fast { get; }
        public static ServiceTierParam Flex { get; }
        public static ServiceTierParam Priority { get; }
        public readonly bool Equals(ServiceTierParam other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(ServiceTierParam left, ServiceTierParam right);
        public static implicit operator ServiceTierParam(string value);
        public static implicit operator ServiceTierParam?(string value);
        public static bool operator !=(ServiceTierParam left, ServiceTierParam right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public readonly partial struct ServiceTierResource : IEquatable<ServiceTierResource> {
        public ServiceTierResource(string value);
        public static ServiceTierResource Auto { get; }
        public static ServiceTierResource Default { get; }
        public static ServiceTierResource Fast { get; }
        public static ServiceTierResource Flex { get; }
        public static ServiceTierResource Priority { get; }
        public readonly bool Equals(ServiceTierResource other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(ServiceTierResource left, ServiceTierResource right);
        public static implicit operator ServiceTierResource(string value);
        public static implicit operator ServiceTierResource?(string value);
        public static bool operator !=(ServiceTierResource left, ServiceTierResource right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public class TextFormatParam : IJsonModel<TextFormatParam>, IPersistableModel<TextFormatParam> {
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
    }
    [Experimental("OPENAI001")]
    public class TextFormatParamJsonSchema : TextFormatParam, IJsonModel<TextFormatParamJsonSchema>, IPersistableModel<TextFormatParamJsonSchema> {
        public TextFormatParamJsonSchema();
        public TextFormatParamJsonSchema(BinaryData schema);
        public BinaryData Schema { get; set; }
    }
    [Experimental("OPENAI001")]
    public class TextFormatParamText : TextFormatParam, IJsonModel<TextFormatParamText>, IPersistableModel<TextFormatParamText> {
        public TextFormatParamText();
    }
    [Experimental("OPENAI001")]
    public class TextFormatResource : IJsonModel<TextFormatResource>, IPersistableModel<TextFormatResource> {
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
    }
    [Experimental("OPENAI001")]
    public class TextFormatResourceJsonSchema : TextFormatResource, IJsonModel<TextFormatResourceJsonSchema>, IPersistableModel<TextFormatResourceJsonSchema> {
        public TextFormatResourceJsonSchema();
        public BinaryData Schema { get; set; }
    }
    [Experimental("OPENAI001")]
    public class TextFormatResourceText : TextFormatResource, IJsonModel<TextFormatResourceText>, IPersistableModel<TextFormatResourceText> {
        public TextFormatResourceText();
    }
    [Experimental("OPENAI001")]
    public readonly partial struct TextFormatType : IEquatable<TextFormatType> {
        public TextFormatType(string value);
        public static TextFormatType JsonSchema { get; }
        public static TextFormatType Text { get; }
        public readonly bool Equals(TextFormatType other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(TextFormatType left, TextFormatType right);
        public static implicit operator TextFormatType(string value);
        public static implicit operator TextFormatType?(string value);
        public static bool operator !=(TextFormatType left, TextFormatType right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public class TextParam : IJsonModel<TextParam>, IPersistableModel<TextParam> {
        public TextFormatParam Format { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public VerbosityParam? Verbosity { get; set; }
    }
    [Experimental("OPENAI001")]
    public class TextResource : IJsonModel<TextResource>, IPersistableModel<TextResource> {
        public TextFormatResource Format { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public VerbosityResource Verbosity { get; set; }
    }
    [Experimental("OPENAI001")]
    public readonly partial struct VerbosityParam : IEquatable<VerbosityParam> {
        public VerbosityParam(string value);
        public static VerbosityParam High { get; }
        public static VerbosityParam Low { get; }
        public static VerbosityParam Medium { get; }
        public readonly bool Equals(VerbosityParam other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(VerbosityParam left, VerbosityParam right);
        public static implicit operator VerbosityParam(string value);
        public static implicit operator VerbosityParam?(string value);
        public static bool operator !=(VerbosityParam left, VerbosityParam right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public readonly partial struct VerbosityResource : IEquatable<VerbosityResource> {
        public VerbosityResource(string value);
        public static VerbosityResource High { get; }
        public static VerbosityResource Low { get; }
        public static VerbosityResource Medium { get; }
        public readonly bool Equals(VerbosityResource other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(VerbosityResource left, VerbosityResource right);
        public static implicit operator VerbosityResource(string value);
        public static implicit operator VerbosityResource?(string value);
        public static bool operator !=(VerbosityResource left, VerbosityResource right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public readonly partial struct WebSearchContextSizeParam : IEquatable<WebSearchContextSizeParam> {
        public WebSearchContextSizeParam(string value);
        public static WebSearchContextSizeParam High { get; }
        public static WebSearchContextSizeParam Low { get; }
        public static WebSearchContextSizeParam Medium { get; }
        public readonly bool Equals(WebSearchContextSizeParam other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(WebSearchContextSizeParam left, WebSearchContextSizeParam right);
        public static implicit operator WebSearchContextSizeParam(string value);
        public static implicit operator WebSearchContextSizeParam?(string value);
        public static bool operator !=(WebSearchContextSizeParam left, WebSearchContextSizeParam right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public readonly partial struct WebSearchContextSizeResource : IEquatable<WebSearchContextSizeResource> {
        public WebSearchContextSizeResource(string value);
        public static WebSearchContextSizeResource High { get; }
        public static WebSearchContextSizeResource Low { get; }
        public static WebSearchContextSizeResource Medium { get; }
        public readonly bool Equals(WebSearchContextSizeResource other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(WebSearchContextSizeResource left, WebSearchContextSizeResource right);
        public static implicit operator WebSearchContextSizeResource(string value);
        public static implicit operator WebSearchContextSizeResource?(string value);
        public static bool operator !=(WebSearchContextSizeResource left, WebSearchContextSizeResource right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public class WebSearchLocationParam : IJsonModel<WebSearchLocationParam>, IPersistableModel<WebSearchLocationParam> {
        public string City { get; set; }
        public string Country { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public string Region { get; set; }
        public string Timezone { get; set; }
    }
    [Experimental("OPENAI001")]
    public class WebSearchLocationResource : IJsonModel<WebSearchLocationResource>, IPersistableModel<WebSearchLocationResource> {
        public string City { get; set; }
        public string Country { get; set; }
        [Serialization.JsonIgnore]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Experimental("SCME0001")]
        public ref JsonPatch Patch { get; }
        public string Region { get; set; }
        public string Timezone { get; set; }
    }
    [Experimental("OPENAI001")]
    public readonly partial struct WebSearchModeParam : IEquatable<WebSearchModeParam> {
        public WebSearchModeParam(string value);
        public static WebSearchModeParam Cached { get; }
        public static WebSearchModeParam Disabled { get; }
        public static WebSearchModeParam Live { get; }
        public readonly bool Equals(WebSearchModeParam other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(WebSearchModeParam left, WebSearchModeParam right);
        public static implicit operator WebSearchModeParam(string value);
        public static implicit operator WebSearchModeParam?(string value);
        public static bool operator !=(WebSearchModeParam left, WebSearchModeParam right);
        public override readonly string ToString();
    }
    [Experimental("OPENAI001")]
    public readonly partial struct WebSearchModeResource : IEquatable<WebSearchModeResource> {
        public WebSearchModeResource(string value);
        public static WebSearchModeResource Cached { get; }
        public static WebSearchModeResource Disabled { get; }
        public static WebSearchModeResource Live { get; }
        public readonly bool Equals(WebSearchModeResource other);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly bool Equals(object obj);
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override readonly int GetHashCode();
        public static bool operator ==(WebSearchModeResource left, WebSearchModeResource right);
        public static implicit operator WebSearchModeResource(string value);
        public static implicit operator WebSearchModeResource?(string value);
        public static bool operator !=(WebSearchModeResource left, WebSearchModeResource right);
        public override readonly string ToString();
    }
}