# This workflow is triggered by the user and runs live tests on the codebase.
name: Live Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled

permissions:
  contents: read

jobs:
  test:
    name: Live Test
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'live test')
    environment: Live Testing
    env:
      version_suffix_args: ${{ format('/p:VersionSuffix="alpha.{0}"', github.run_number) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup .NET 10
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          global-json-file: global.json

      - name: Setup .NET 9
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: '9.x'

      - name: Setup .NET 8
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: '8.x'

      - name: Restore tools
        run: dotnet tool restore

      - name: Run tests in Playback mode
        run: dotnet test ./tests/OpenAI.Tests.csproj
          --configuration Release
          --logger "trx;LogFilePrefix=playback"
          --results-directory ${{ github.workspace }}/artifacts/test-results
          ${{ env.version_suffix_args }}
        env:
          CLIENTMODEL_TEST_MODE: Playback
          CLIENTMODEL_DISABLE_AUTO_RECORDING: true

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ !cancelled() }}
        with:
          name: test-artifacts
          path: ${{github.workspace}}/artifacts
